---
- name: Restart service systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted

- name: Restart service crowdsec-firewall-bouncer
  ansible.builtin.service:
    name: crowdsec-firewall-bouncer
    state: restarted
