---
ubuntu_version: jammy

apt_base_packages:
  - sudo
  - mc
  - vim
  - git
  - net-tools
  - util-linux
  - screen
  - tmux
  - mdadm
  - hdparm
  - htop

apt_developer_packages:
  - make
  - pre-commit
  - terraform
  - shellcheck
  - tshark

apt_packages: apt_base_packages + apt_developer_packages # TODO

smb_shares:
  - media
  - family-media
  - backup
  - downloads
