---
ubuntu_version: jammy

base_packages:
  - sudo
  - mc
  - vim
  - git
  - net-tools
  - util-linux
  - screen
  - tmux
  - mdadm
  - hdparm
  - htop
  - make
  - shellcheck

smb_shares:
  - media
  - family-media
  - backup
  - downloads
