---

# kics-scan ignore-line
admin_password: "XXX"

# sha512_crypt requires <= 16 chars for salt. Generate with:
#   tr -dc 'A-Za-z0-9./' < /dev/urandom | head -c 16
password_salt: "XXX"

debian_base_crowdsec_local_api_key: "XXX"
