# The Cloud Native Application Proxy
#
# https://traefik.io/
# https://github.com/traefik/traefik
# https://blog.lrvt.de/nginx-proxy-manager-versus-traefik/
---
version: "3.5"
name: traefik
services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    restart: unless-stopped
    environment:
      TZ: ${TIMEZONE}
      #OVH_ENDPOINT: ${OVH_ENDPOINT}
      #OVH_APPLICATION_KEY: ${OVH_APPLICATION_KEY}
      #OVH_APPLICATION_SECRET: ${OVH_APPLICATION_SECRET}
      #OVH_CONSUMER_KEY: ${OVH_CONSUMER_KEY}
      CLOUDFLARE_DNS_API_TOKEN: ${CLOUDFLARE_DNS_API_TOKEN}
      MYDOMAIN: ${MYDOMAIN}
      MYEMAIL: ${MYEMAIL}
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik/
      - ${DOCKER_VOLUMES}/traefik/logs:/logs
      - ${DOCKER_VOLUMES}/traefik/letsencrypt:/letsencrypt
    ports:
      - 80:80 # HTTP
      - 443:443/tcp # HTTPS
      - 443:443/udp # HTTP/3 - QUIC
      # - 81:8080 # API MGMT UI (enabled by --api.insecure=true)
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.api.rule: Host(`traefik.${MYDOMAIN}`) # Define the subdomain for the traefik dashboard.
      traefik.http.routers.api.service: api@internal # Enable Traefik API.
      traefik.http.routers.api.middlewares: https-local@file
      homepage.group: Infra
      homepage.name: Traefik
      homepage.icon: traefik.png
      homepage.href: https://traefik.${MYDOMAIN}/
      homepage.description: The Cloud Native Application Proxy
      homepage.widget.type: traefik
      homepage.widget.url: https://traefik.${MYDOMAIN}/

networks:
  proxy:
    external: true