---
- name: Install SMB packages
  ansible.builtin.apt:
    pkg:
      - smbclient
      - cifs-utils
    state: present

- name: Create credentials file
  ansible.builtin.copy:
    dest: "{{ smb_credentials_file }}"
    content: |
      username={{ admin_user }}
      password={{ admin_password }}
    owner: root
    group: root
    mode: '0600'

- name: Create mount base directory
  ansible.builtin.file:
    path: "{{ smb_mnt_dir }}"
    state: directory
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: '0777'

- name: Create mount directories
  ansible.builtin.file:
    path: "{{ smb_mnt_dir }}{{ item }}"
    state: directory
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: '0777'
  loop: "{{ smb_shares }}"

- name: Mount shares from NAS
  ansible.posix.mount:
    src: "//{{ smb_hostname }}/{{ item }}"
    path: "{{ smb_mnt_dir }}{{ item }}"
    fstype: cifs
    opts: "{{ smb_mount_opts }}"
    state: mounted
  loop: "{{ smb_shares }}"
