---
- name: Mount network shares
  become: true
  block:
    - name: Mount network shares
      ansible.builtin.include_tasks: 10-samba.yaml
      when:
        - debian_samba_client_servers is defined
        - debian_samba_client_servers | length > 0
