# Docker service configuration for myhost
# yaml-language-server: $schema=../services-schema.yaml
---
services:
  - security:
      - name: crowdsec
        state: up
      - name: traefik
        state: up
      - name: authentik
        state: up
      - name: wg-easy
        state: up
      - name: cloudflared
        state: up
      - name: endlessh
        state: up
      - name: frigate
        state: up

  - dashboard:
      - name: homepage
        state: up

  - infra:
      - name: portainer
        state: down
      - name: adguardhome
        state: up
      - name: adguardhome-sync
        state: up
      - name: unifi-network-application
        state: up
      - name: ddclient
        state: up

  - monitoring:
      - name: scrutiny
        state: up
      - name: uptime-kuma
        state: up
      - name: prometheus
        state: up
      - name: grafana
        state: up

  - automation:
      - name: homeassistant
        state: up
      - name: n8n
        state: up
      - name: mosquitto
        state: up
      - name: esphome-device-builder
        state: up

  - media/video:
      - name: jellyfin
        state: up
      - name: metube
        state: up

  - media/photo:
      - name: immich
        state: up

  - media/audio:
      - name: navidrome
        state: up

  - media/ebook:
      - name: calibre
        state: down
      - name: calibre-web-automated
        state: up
      - name: kiwix-serve
        state: up

  - storage:
      - name: samba
        state: up
  #     - name: syncthing
  #       state: up
  #     - name: minio
  #       state: down
  #     - name: webdav
  #       state: up
  #     - name: bees
  #       state: down

  - database:
      - name: adminer
        state: up
      - name: couchdb
        state: up
      - name: mongodb
        state: up
      - name: postgresql
        state: up
      - name: mssql-server
        state: down

  - backup:
      - name: kopia-b2
        state: up

  - dev:
      - name: code-server
        state: up
      - name: gitea
        state: up
      - name: act-runner
        state: up
      - name: gitlab
        state: down
      - name: jupyter-notebook
        state: down
      - name: supabase
        state: down
      - name: httpbin
        state: up
      - name: dev-sites
        state: up

  - tools:
      - name: homelab-docs
        state: up
      - name: vaultwarden
        state: up
      - name: openspeedtest
        state: up
      - name: cyberchef
        state: up
      - name: guacamole
        state: up
      - name: kasm
        state: down
      - name: stirling-pdf
        state: down
      - name: searxng
        state: up
      - name: firefox
        state: down
      - name: obsidian
        state: up
      - name: scanservjs
        state: up

  - ai:
      - name: ollama
        state: up
      - name: litellm
        state: up
      - name: open-webui
        state: up
      - name: open-webui-pipelines
        state: down
      - name: autogenstudio
        state: down
      - name: sillytavern
        state: down
      - name: qdrant
        state: up

  - communication:
      - name: mattermost
        state: up

  - fileshare:
      - name: qbittorrent
        state: up

  # - arr:
  #     - name: radarr
  #       state: down
  #     - name: sonarr
  #       state: down
  #     - name: bazarr
  #       state: down
  #     - name: prowlarr
  #       state: down
  #     - name: jellyseerr
  #       state: down
  #     - name: flaresolverr
  #       state: down

  # - game:
  #     - name: legendary-minecraft
  #       state: down

  - personal:
      - name: personal-web
        state: up
      - name: tales
        state: down
