# Home Assistant Core - Open source home automation that puts local control and privacy first. Powered by a worldwide community of tinkerers and DIY enthusiasts. Perfect to run on a Raspberry Pi or a local server.
#
# Home Assistant needs to set up to allow the Traefik reverse proxy (details: https://www.home-assistant.io/integrations/http/)
# For this, add to `${DOCKER_VOLUMES}/homeassistant/configuration.yaml`:
# ```
# http:
#   use_x_forwarded_for: true
#   trusted_proxies:
#     - 172.18.0.0/24
# ```
#
# 🏠 Home: https://www.home-assistant.io/  
# 📦 Image: https://hub.docker.com/r/linuxserver/homeassistant  
---
name: homeassistant
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:2024.8.2
    container_name: homeassistant
    restart: unless-stopped
    network_mode: host
    hostname: ${MAIN_NODE}
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - ${DOCKER_VOLUMES}/homeassistant:/config
    expose:
      - 8123 # Web UI
    # devices:
    #   - /path/to/device:/path/to/device #optional
    labels:
      traefik.enable: true
      traefik.http.routers.homeassistant.entrypoints: websecure
      traefik.http.routers.homeassistant.middlewares: https-local@file
      traefik.http.routers.homeassistant.rule: Host(`ha.${MYDOMAIN}`)
      traefik.http.services.homeassistant.loadbalancer.server.port: 8123
      homepage.group: Automation
      homepage.name: HomeAssistant
      homepage.icon: home-assistant.png
      homepage.href: https://ha.${MYDOMAIN}/
      homepage.description: Open source home automation
