"""Render and deploy the configured Docker host."""

import os
import shlex
import time
from pathlib import Path

import yaml

from .core import ROOT, SERVICE_CONTAINERS, BootstrapError, BootstrapPlan, Runner, private_key_for, vm_ssh_command
from .proxmox import discover_vm_ipv4, establish_ssh_trust, provision_vm, verify_dns, with_expected_ipv4


def atomic_write(path: Path, content: str, mode: int = 0o600) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    try:
        descriptor = os.open(temporary, os.O_WRONLY | os.O_CREAT | os.O_EXCL, mode)
        with os.fdopen(descriptor, "w") as file:
            file.write(content)
        os.replace(temporary, path)
        path.chmod(mode)
    finally:
        temporary.unlink(missing_ok=True)


def render_services(services: tuple[str, ...]) -> str:
    categories: dict[str, list[dict[str, str]]] = {}
    for service in services:
        category, name = service.rsplit("/", 1)
        categories.setdefault(category, []).append({"name": name, "state": "up"})
    return yaml.safe_dump({"services": [{category: entries} for category, entries in categories.items()]}, sort_keys=False)


def render_vm_config(plan: BootstrapPlan, expected_ipv4: str, root: Path = ROOT) -> None:
    vm_dir = root / "config/vm/proxmox"
    atomic_write(vm_dir / "bootstrap-authorized-key.pub", plan.config.vm.ssh_public_key.read_text(), 0o600)
    config = plan.config
    atomic_write(
        vm_dir / "ubuntu-cloud.env",
        f"""# Generated by bootstrap. Do not edit manually.
PROXMOX_HOST={config.proxmox.ssh_target}
UBUNTU_VERSION={config.vm.ubuntu_version}
USERNAME={config.vm.username}
VMNAME={config.vm.name}
VMID={plan.vm_id}
CPU_CORES={config.vm.cpu_cores}
MAX_MEMORY_SIZE={config.vm.memory_max_mib}
MIN_MEMORY_SIZE={config.vm.memory_min_mib}
DISK_SIZE={config.vm.disk_size}
VM_STORAGE={config.vm.storage}
VM_BRIDGE={config.vm.bridge}
VM_MAC={plan.mac}
EXPECTED_IPV4={expected_ipv4}
SSH_PUBLIC_KEY_FILE=/tmp/vm/proxmox/bootstrap-authorized-key.pub
""",
    )


def render_config(plan: BootstrapPlan, root: Path = ROOT, expected_ipv4: str | None = None) -> None:
    expected_ipv4 = expected_ipv4 or plan.config.network.expected_ipv4
    if expected_ipv4 is None:
        raise BootstrapError("Cannot render host configuration before the VM IPv4 address is known")
    render_vm_config(plan, expected_ipv4, root)
    inventory_path = root / "config/ansible/inventory/inventory.yaml"
    inventory = (
        yaml.safe_load(inventory_path.read_text())
        if inventory_path.exists()
        else yaml.safe_load((root / "config-example/ansible/inventory/inventory.yaml").read_text())
    )
    inventory = inventory or {}
    config, name = plan.config, plan.config.vm.name
    hosts = inventory.setdefault("debian", {}).setdefault("hosts", {})
    existing = hosts.get(name)
    desired: dict[str, object] = {
        "ansible_host": expected_ipv4,
        "ansible_user": config.vm.username,
        "debian_base_ssh_key_file": str(config.vm.ssh_public_key),
        "debian_docker_host_volumes_path": config.host.docker_volumes,
    }
    if private_key := private_key_for(config.vm.ssh_public_key):
        desired["ansible_ssh_private_key_file"] = str(private_key)
    if existing is not None and not isinstance(existing, dict):
        raise BootstrapError(f"Inventory host has an invalid value: {name}")
    for key, value in desired.items():
        if existing and key in existing and existing[key] != value:
            raise BootstrapError(f"Inventory host has a conflicting {key}: {name}")
    hosts[name] = {**(existing or {}), **desired}
    docker_hosts = inventory.setdefault("docker_hosts", {}).setdefault("hosts", {})
    if not isinstance(docker_hosts, dict):
        raise BootstrapError("docker_hosts.hosts must be a mapping")
    docker_hosts.setdefault(name, None)
    atomic_write(inventory_path, yaml.safe_dump(inventory, sort_keys=False))
    docker_dir = root / f"config/docker/{name}"
    atomic_write(
        docker_dir / ".env",
        f"""# Generated by bootstrap. Do not edit manually.
TIMEZONE={config.host.timezone}
MYDOMAIN={config.network.domain}
ADMIN_EMAIL={config.tls.acme_email}
DOCKER_VOLUMES={config.host.docker_volumes}
STORAGE_BACKGROUNDS=${{DOCKER_VOLUMES}}/homepage/backgrounds
CROWDSEC_ENABLED=false
""",
    )
    atomic_write(docker_dir / ".env.traefik", f"CLOUDFLARE_DNS_API_TOKEN={config.tls.token}\nCROWDSEC_BOUNCER_API_KEY=\n")
    atomic_write(docker_dir / "services.yaml", render_services(config.deployment.services))


def configure_host(plan: BootstrapPlan, runner: Runner) -> None:
    runner.run(["ansible/apply-homelab.sh", "--limit", plan.config.vm.name], timeout=1800)
    name = shlex.quote(plan.config.vm.name)
    runner.run(
        vm_ssh_command(
            plan,
            f'docker info >/dev/null && docker compose version >/dev/null && task --version >/dev/null && test "$(hostname --short)" = {name} && test "$(hostname)" = {name}',
        )
    )


def prepare_remote_repository(plan: BootstrapPlan, runner: Runner, root: Path = ROOT) -> None:
    checkout, repository = "$HOME/repos/infra", plan.repository
    branch, url = shlex.quote(repository.branch), shlex.quote(repository.url)
    state = runner.run(
        vm_ssh_command(
            plan, f"if test -d {checkout}/.git; then printf repository; elif test -e {checkout}; then printf invalid; else printf missing; fi"
        ),
        capture=True,
        timeout=30,
    )
    if state == "invalid":
        raise BootstrapError(f"Remote checkout path exists but is not a Git repository: {checkout}")
    if state == "missing":
        runner.run(vm_ssh_command(plan, f"mkdir -p $HOME/repos; git clone --branch {branch} --single-branch {url} {checkout}"), timeout=300)
    elif state == "repository":
        update = f'test -z "$(git -C {checkout} status --porcelain --untracked-files=no)" && test "$(git -C {checkout} branch --show-current)" = {branch} && git -C {checkout} fetch origin {branch} && git -C {checkout} merge --ff-only {shlex.quote(repository.commit)}'
        runner.run(vm_ssh_command(plan, update), timeout=300)
    else:
        raise BootstrapError("Could not determine the remote repository state")
    runner.run(vm_ssh_command(plan, f'test "$(git -C {checkout} rev-parse HEAD)" = {shlex.quote(repository.commit)}'), timeout=30)
    services_path = f"{checkout}/config/docker/{plan.config.vm.name}/services.yaml"
    if runner.run(vm_ssh_command(plan, f"test -f {services_path} && printf yes || true"), capture=True) != "yes":
        runner.run(vm_ssh_command(plan, f"cd {checkout} && task bootstrap:init-local-config"))
    target = f"{plan.config.vm.username}@{plan.config.network.expected_ipv4}:repos/infra/config/docker/{plan.config.vm.name}/"
    transport = "ssh -o BatchMode=yes" + (f" -i {shlex.quote(str(key))}" if (key := private_key_for(plan.config.vm.ssh_public_key)) else "")
    runner.run(["rsync", "-a", "-e", transport, f"{root}/config/docker/{plan.config.vm.name}/", target], timeout=120)
    runner.run(vm_ssh_command(plan, f"chmod 600 {checkout}/config/docker/{plan.config.vm.name}/.env.traefik"))
    runner.run(vm_ssh_command(plan, f"cd {checkout} && task docker:check-host"))


def deploy_services(plan: BootstrapPlan, runner: Runner) -> None:
    runner.run(vm_ssh_command(plan, "cd $HOME/repos/infra && task docker:apply"), timeout=1800)


def verify_services(plan: BootstrapPlan, runner: Runner, timeout: int = 180) -> None:
    containers, checkout = " ".join(SERVICE_CONTAINERS), "$HOME/repos/infra"
    status = f"docker inspect --format '{{{{.State.Running}}}}:{{{{.RestartCount}}}}' {containers}"
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        try:
            statuses = runner.run(vm_ssh_command(plan, status), capture=True, timeout=20).splitlines()
            if len(statuses) == len(SERVICE_CONTAINERS) and all(entry.startswith("true:") for entry in statuses):
                for url in (f"https://home.{plan.config.network.domain}/", f"https://traefik.{plan.config.network.domain}/dashboard/"):
                    runner.run(
                        ["curl", "--fail", "--silent", "--show-error", "--connect-timeout", "5", "--max-time", "15", "--output", "/dev/null", url],
                        timeout=20,
                    )
                break
        except BootstrapError:
            pass
        time.sleep(5)
    else:
        raise BootstrapError("Core services did not become stable and reachable before the timeout")
    before = runner.run(vm_ssh_command(plan, status), capture=True, timeout=20)
    time.sleep(10)
    if before != runner.run(vm_ssh_command(plan, status), capture=True, timeout=20):
        raise BootstrapError("Core containers did not remain stable during the acceptance interval")
    persistence = f"test -s {shlex.quote(plan.config.host.docker_volumes)}/traefik/letsencrypt/acme.json && test -d {shlex.quote(plan.config.host.docker_volumes)}/traefik/logs && test -d {shlex.quote(plan.config.host.docker_volumes)}/homepage/logs"
    runner.run(vm_ssh_command(plan, persistence))
    ids = f"docker inspect --format '{{{{.Id}}}}' {containers}"
    before = runner.run(vm_ssh_command(plan, ids), capture=True, timeout=20)
    runner.run(vm_ssh_command(plan, f"cd {checkout} && task docker:apply"), timeout=1800)
    if before != runner.run(vm_ssh_command(plan, ids), capture=True, timeout=20):
        raise BootstrapError("Repeat deployment unexpectedly recreated core containers")


def apply(plan: BootstrapPlan, runner: Runner, *, assume_yes: bool = False, root: Path = ROOT) -> None:
    if not assume_yes and input(
        f"Create or resume VM {plan.config.vm.name} (ID {plan.vm_id}) and deploy core services? [y/N] "
    ).strip().lower() not in {"y", "yes"}:
        raise BootstrapError("Bootstrap cancelled")
    print("[1/7] Rendering VM configuration")
    render_vm_config(plan, plan.config.network.expected_ipv4 or "", root)
    print("[2/7] Provisioning or resuming the VM")
    provision_vm(plan, runner)
    expected_ipv4 = plan.config.network.expected_ipv4
    if expected_ipv4 is None:
        expected_ipv4 = discover_vm_ipv4(plan, runner)
        print(f"Discovered VM {plan.vm_id} IPv4 address: {expected_ipv4}")
        verify_dns(plan, expected_ipv4, discovered=True)
        plan = with_expected_ipv4(plan, expected_ipv4)
    print("[3/7] Rendering host configuration")
    render_config(plan, root, expected_ipv4)
    print("[4/7] Verifying and trusting the VM SSH host key")
    establish_ssh_trust(plan, runner)
    print("[5/7] Configuring the Docker host with Ansible")
    configure_host(plan, runner)
    print("[6/7] Preparing the remote repository and service configuration")
    prepare_remote_repository(plan, runner, root)
    print("[7/7] Deploying services")
    deploy_services(plan, runner)
    print("Verifying service health, TLS, DNS, persistence, and repeat deployment")
    verify_services(plan, runner)
    print("Bootstrap completed successfully.")
