# Code-server is VS Code running on a remote server, accessible through the browser.
#
# https://hub.docker.com/r/linuxserver/code-server
# https://github.com/coder/code-server
# https://github.com/coder/code-server/blob/main/docs/FAQ.md
---
version: "3.5"
name: code-server
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
      PASSWORD: #optional
      HASHED_PASSWORD: #optional
      SUDO_PASSWORD: ${ADMIN_PASSWORD} #optional
      SUDO_PASSWORD_HASH:  #optional
      PROXY_DOMAIN: code.${MYDOMAIN} #optional
      DEFAULT_WORKSPACE: /config/workspace #optional
    volumes:
      - ${DOCKER_VOLUMES}/code-server:/config
      - ${ADMIN_HOME}/repos:/config/repos
      # TODO - ${ADMIN_HOME}/.ssh: ...
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.code.entrypoints: websecure
      traefik.http.routers.code.middlewares: https-local-auth@file
      traefik.http.routers.code.rule: Host(`code.${MYDOMAIN}`)
      traefik.http.services.code.loadbalancer.server.port: 8443
      homepage.group: Tools
      homepage.name: Code-Server
      homepage.icon: code.png
      homepage.href: https://code.${MYDOMAIN}/
      homepage.description: "[SSO] Visual Studio Code"

networks:
  proxy:
    external: true
