ARG BASE_IMAGE=debian:bookworm-slim
FROM ${BASE_IMAGE}

WORKDIR /tmp/ansible-bootstrap-container

# Setup Ansible

COPY bootstrap-ansible.sh ansible.cfg requirements.yml ./
RUN ./bootstrap-ansible.sh && \
    apt-get clean

# Copy Ansible directory

COPY . .

# Setup debian-base role

ARG ADMIN_USER=buba
ARG ADMIN_PASSWORD=InItIal_PswD

RUN mkdir -p inventory/host_vars/local-debian/ && \
    LOCAL_CONFIG=inventory/host_vars/local-debian/local.yaml && \
    echo admin_user: ${ADMIN_USER} > $LOCAL_CONFIG && \
    echo admin_password: ${ADMIN_PASSWORD} >> $LOCAL_CONFIG && \
    echo configure_hosts_file: false >> $LOCAL_CONFIG && \
    echo configure_ssh_key: false >> $LOCAL_CONFIG && \
    ./apply-adhoc.sh local-debian debian-base && \
    rm -rf .fact_cache && \
    apt-get clean

# Linuxbrew installation is per-user

USER ${ADMIN_USER}

RUN ./apply-adhoc.sh local-debian markosamuli.linuxbrew,debian-developer && \
    sudo apt-get clean

WORKDIR /home/${ADMIN_USER}
