# https://taskfile.dev/ - Task is a task runner / build tool that aims to be simpler and easier to use than, for example, GNU Make.
# [Say Goodbye to Makefile - Use Taskfile to Manage Tasks in CI/CD Pipelines and Locally](https://www.youtube.com/watch?v=Z7EnwBaJzCk)
# Installed via the `debian-developer` Ansible role.

version: '3'

tasks:
  default:
    cmds:
      - task --list-all

  ### Development-related tasks

  lint:
    cmds:
      - pre-commit run --all-files

  create-example-env:
    dotenv: ['docker/hosts/.env']
    cmds:
      - scripts/create-example-env.py docker/hosts/.env > docker/hosts/.env.example
      - scripts/create-example-env.py docker/hosts/${MAIN_NODE}/.env > docker/hosts/example/.env
    sources:
      - docker/hosts/.env
      - docker/hosts/${MAIN_NODE}/.env
    generates:
      - docker/hosts/.env.example
      - docker/hosts/example/.env

  docs-build:
    cmds:
      - docs/web/build.sh

  docs-deploy:
    cmds:
      - task: docs-build
      - task: docker-command
        vars:
          STACK: tools
          SERVICE: homelab-docs
          COMMAND: recreate

  ### Operations-related tasks

  docker-command:
    internal: true
    cmds:
      - cd "docker/hosts/$(hostname | tr '[:upper:]' '[:lower:]')" && bash -c "source ../../common.sh; {{.COMMAND}} {{.STACK}} {{.SERVICE}}"

  docker-apply:
    cmds:
      - docker/apply-local.sh

  docker-update:
    cmds:
      - UPDATE=true docker/apply-local.sh

  docker-stop-all:
    cmds:
      - docker stop $(docker ps -a -q)

  docker-check-updates:
    cmds:
      - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --run-once --cleanup --monitor-only

  crowdsec-collections:
    cmds:
      - docker exec crowdsec cscli collections list
  crowdsec-bouncers:
    cmds:
      - docker exec crowdsec cscli bouncers list
  crowdsec-decisions:
    cmds:
      - docker exec crowdsec cscli decisions list
  crowdsec-alerts:
    cmds:
      - docker exec crowdsec cscli alerts list
  crowdsec-metrics:
    cmds:
      - docker exec crowdsec cscli metrics

  star-github-repos:
    dotenv: ['docker/hosts/.env']
    preconditions:
      - sh: "[ ! -z \"${GITHUB_API_TOKEN}\" ]"
        msg: GITHUB_API_TOKEN environment variable must be set (exported)
    cmds:
      - scripts/github-extract-links.py . | scripts/github-star-repo.py`

