# https://taskfile.dev/ - Task is a task runner / build tool that aims to be simpler and easier to use than, for example, GNU Make.
# [Say Goodbye to Makefile - Use Taskfile to Manage Tasks in CI/CD Pipelines and Locally](https://www.youtube.com/watch?v=Z7EnwBaJzCk)
# Installed via the `debian-developer` Ansible role.

version: '3'

includes:
  crowdsec: ./docker/stacks/security/Taskfile.crowdsec.yaml
  devcontainer: ./Taskfile.dev.yaml

tasks:
  default:
    desc: List all tasks
    cmds:
      - task --list-all

  # TaskUI is a lightweight terminal user interface for executing tasks defined using taskfile.dev.
  # https://github.com/thmshmm/taskui
  ui:
    desc: Open terminal user interface for executing tasks (TaskUI)
    env:
      TASKUI_HIGHLIGHT_STYLE_BG: "#00cc66"
      TASKUI_HIGHLIGHT_STYLE_FG: "#4c4f69"
    cmds:
      - taskui

  ### Development-related tasks

  lint:
    desc: Run linting tools (via pre-commit)
    cmds:
      - pre-commit run --all-files

  create-example-env:
    desc: Create/update Docker example environment files
    dotenv: ['docker/hosts/.env']
    cmds:
      - scripts/create-example-env.py docker/hosts/.env > docker/hosts/.env.example
      - scripts/create-example-env.py docker/hosts/${MAIN_NODE}/.env > docker/hosts/example/.env
    sources:
      - docker/hosts/.env
      - docker/hosts/${MAIN_NODE}/.env
    generates:
      - docker/hosts/.env.example
      - docker/hosts/example/.env

  pre-commit-update:
    desc: Update pre-commit repositories
    cmds:
      - pre-commit autoupdate

  git-rebase-fixup:
    desc: Interactively rebase current branch to origin (stash, rebase, pop)
    cmds:
      - git stash
      - GIT_SEQUENCE_EDITOR=scripts/git-rebase-fixup.py git rebase -i origin/$(git branch --show-current)
      - git stash pop

  build:
    desc: Run all linting and build tasks
    cmds:
      - task: create-example-env
      - task: docs-deploy
      - task: pre-commit-update
      - task: lint

  docs-build:
    desc: Build documentation site container
    dotenv: ['docker/hosts/.env']
    cmds:
      - |
        SITE_DOMAIN=docs.${MYDOMAIN}
        HUGO_BASEURL=https://${SITE_DOMAIN}
        TAG=${SITE_DOMAIN}:latest
        docker build -f docs/web/Dockerfile -t "${TAG}" --build-arg HUGO_BASEURL="${HUGO_BASEURL}" .

  docs-deploy:
    desc: Build and deploy documentation site
    cmds:
      - task: docs-build
      - task: docker-command
        vars:
          STACK: tools
          SERVICE: homelab-docs
          COMMAND: recreate

  ### Operations-related tasks

  get-public-ip:
    desc: Display public IP (ipinfo.io)
    cmds:
      - curl -s https://ipinfo.io/ip

  versions:
    desc: Show software version numbers
    cmds:
      - uname -a
      - lsb_release -a
      - docker --version

  docker-command:
    internal: true
    cmds:
      - cd "docker/hosts/$(hostname | tr '[:upper:]' '[:lower:]')" && bash -c "source ../../common.sh; {{.COMMAND}} {{.STACK}} {{.SERVICE}}"

  docker-apply:
    desc: Deploy locally configured containers
    cmds:
      - docker/apply-local.sh

  docker-update:
    desc: Update and restart containers
    cmds:
      - UPDATE=true docker/apply-local.sh

  docker-stop-all:
    desc: Stop all running containers
    cmds:
      - docker stop $(docker ps -a -q)

  docker-check-updates:
    desc: Run Watchtower to get updated container images
    cmds:
      - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --run-once --cleanup --monitor-only

  star-github-repos:
    desc: Add star to all referenced GitHub repos
    dotenv: ['docker/hosts/.env']
    preconditions:
      - sh: "[ ! -z \"${GITHUB_API_TOKEN}\" ]"
        msg: GITHUB_API_TOKEN environment variable must be set (exported)
    cmds:
      - scripts/github-extract-links.py . | sort | uniq | scripts/github-star-repo.py`

  ansible-apply-homelab:
    desc: Run 'homelab' Ansible playbook
    cmds:
      - ansible/apply-homelab.sh

  ansible-apply-cloud:
    desc: Run 'cloud' Ansible playbook
    cmds:
      - ansible/apply-cloud.sh
