---
###############################################################
#                   Authelia configuration                    #
###############################################################

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug

theme: dark

# 'jwt_secret' is set via AUTHELIA_JWT_SECRET_FILE

default_redirection_url: https://auth.example.com

totp:
  issuer: authelia.com

# One-Tap Authentication With Duo Push
# https://duo.com/product/multi-factor-authentication-mfa/authentication-methods/duo-push
# duo_api:
#  hostname: api-123456789.example.com
#  integration_key: ABCDEF
#  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY_FILE
#  secret_key: 1234567890abcdefghifjkl

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64
      
access_control:
  default_policy: deny
  rules:
    - domain: "auth.example.com"
      policy: bypass
    # - domain: "very-secure.example.com" # TODO example
    #   policy: two_factor
    - domain: "*.example.com"
      # subject: 
      #   - "group:admins"
      policy: one_factor

session:
  # 'secret' is set via AUTHELIA_SESSION_SECRET_FILE
  name: authelia_session
  domain: example.com # Should match whatever your root protected domain is
  same_site: lax
  expiration: 8h
  inactivity: 1h
  remember_me_duration: 1M

  # redis:
  #   host: redis
  #   port: 6379
  #   # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
  #   # password: authelia

regulation:
  max_retries: 3
  find_time: 10m
  ban_time: 12h

storage:
  # 'encryption_key' is set via AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE
  local:
    path: /data/db.sqlite3

notifier:
  # smtp:
  #   username: test
  #   # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
  #   password: password
  #   host: mail.example.com
  #   port: 25
  #   sender: admin@example.com
  filesystem:
    filename: /data/notification.txt
