# Sabnzbd makes Usenet as simple and streamlined as possible by automating everything we can. All you have to do is add an .nzb. SABnzbd takes over from there, where it will be automatically downloaded, verified, repaired, extracted and filed away with zero human interaction.
#
# https://sabnzbd.org/
# https://github.com/linuxserver/docker-sabnzbd
---
version: "3.5"
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - ${DOCKER_VOLUMES}/sabnzbd:/config
      - ${STORAGE_DOWNLOADS}/sabnzbd:/downloads #optional
      - ${STORAGE_DOWNLOADS}/sabnzbd-incomplete:/incomplete-downloads #optional
    ports:
      - 8080:8080
