# CyberChef is the Cyber Swiss Army Knife web app for encryption, encoding, compression and data analysis.
#
# 📜 Source: https://github.com/mpepping/docker-cyberchef/  
# 📦 Image: https://hub.docker.com/r/mpepping/cyberchef/  
---
name: cyberchef
services:
  cyberchef:
    image: mpepping/cyberchef:v10.19.4
    container_name: cyberchef
    restart: unless-stopped
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.cyberchef.entrypoints: websecure
      traefik.http.routers.cyberchef.middlewares: https-local@file
      traefik.http.services.cyberchef.loadbalancer.server.port: 8000
      homepage.group: Tools
      homepage.name: Cyberchef
      homepage.icon: cyberchef.png
      homepage.href: https://cyberchef.${MYDOMAIN}/
      homepage.description: Swiss Army Knife web app for data analysis

networks:
  proxy:
    external: true
