# Static website containing the complete documentation of the lab, created from the repo.
# Build the image by running `task docs:build`
---
name: homelab-docs
services:
  homelab-docs:
    image: docs.${MYDOMAIN}:latest
    container_name: homelab-docs
    restart: unless-stopped
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.homelab-docs.middlewares: localaccess@file
      traefik.http.routers.homelab-docs.rule: Host(`docs.${MYDOMAIN}`)
      traefik.http.services.homelab-docs.loadbalancer.server.port: 80
      homepage.group: Tools
      homepage.name: Homelab Documentation
      homepage.icon: hugo.png
      homepage.href: https://docs.${MYDOMAIN}/
      homepage.description: Static website built from the repo
      com.centurylinklabs.watchtower.enable: false

networks:
  proxy:
    external: true
