# Unofficial Bitwarden compatible server written in Rust
#
# 📜 Source: https://github.com/dani-garcia/vaultwarden  
# Wiki: https://github.com/dani-garcia/vaultwarden/wiki  
# Keepass import: https://github.com/dani-garcia/vaultwarden/wiki/Importing-data-from-Keepass-or-KeepassX  
# Bitwarden: https://bitwarden.com/, https://bitwarden.com/browser-start/  
---
name: vaultwarden
services:
  server:
    image: vaultwarden/server:1.34.3
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      LOG_FILE: "/data/vaultwarden.log"
      LOG_LEVEL: "warn"
      EXTENDED_LOGGING: "true"
      IP_HEADER: "X-Forwarded-For"
    volumes:
      - ${DOCKER_VOLUMES}/vaultwarden:/data
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.vault.middlewares: localaccess@file
      traefik.http.routers.vault.rule: Host(`vault.${MYDOMAIN}`)
      traefik.http.services.vault.loadbalancer.server.port: 80
      homepage.group: Tools
      homepage.name: Vaultwarden
      homepage.icon: vaultwarden.png
      homepage.href: https://vault.${MYDOMAIN}/
      homepage.description: Password Manager

networks:
  proxy:
    external: true
