# AdGuard Home is a network-wide software for blocking ads and tracking. After you set it up, it'll cover all your home devices, and you won't need any client-side software for that
#
# To fix "listen tcp4 0.0.0.0:53: bind: address already in use" error on Ubuntu: disable `DNSStubListener` (see Ansible).  
# Follow the AdguardHome installation wizard for first-time configuration. (Note: Firefox may not allow access to the admin interface)
#
# Best practice:
#  1. Configure two instances of AdGuard Home on two separate hardware
#  2. Setup adguardhome-sync to sync the settings
#  3. Specify both DNS servers in the router's DHCP settings
#
# 🏠 Home: https://adguard.com/en/adguard-home/overview.html  
# 📦 Image: https://hub.docker.com/r/adguard/adguardhome  
---
name: adguardhome
services:
  adguardhome:
    image: adguard/adguardhome:v0.107.69
    container_name: adguardhome
    restart: unless-stopped
    volumes:
      - ${DOCKER_VOLUMES}/adguardhome/work:/opt/adguardhome/work
      - ${DOCKER_VOLUMES}/adguardhome/conf:/opt/adguardhome/conf
    ports:
      # Fix for DNS access from containers
      # https://github.com/AdguardTeam/AdGuardHome/discussions/6252
      - "${LOCAL_NODE_IP}:53:53/tcp" # plain DNS
      - "${LOCAL_NODE_IP}:53:53/udp" # plain DNS

      # - 67:67/udp # add if you intend to use AdGuard Home as a DHCP server
      # - 68:68/udp # add if you intend to use AdGuard Home as a DHCP server
      # - 80:80/tcp # add if you are going to use AdGuard Home's admin panel as well as run AdGuard Home as an HTTPS/DNS-over-HTTPS server
      # - 443:443/tcp # add if you are going to use AdGuard Home's admin panel as well as run AdGuard Home as an HTTPS/DNS-over-HTTPS server
      # - 443:443/udp # add if you are going to use AdGuard Home's admin panel as well as run AdGuard Home as an HTTPS/DNS-over-HTTPS server
      - 3000:3000/tcp # add if you are going to use AdGuard Home's admin panel as well as run AdGuard Home as an HTTPS/DNS-over-HTTPS server - Web UI
      # - 853:853/tcp # add if you are going to run AdGuard Home as a DNS-over-TLS server
      # - 784:784/udp # add if you are going to run AdGuard Home as a DNS-over-QUIC server. You may only leave one or two of these
      # - 853:853/udp # add if you are going to run AdGuard Home as a DNS-over-QUIC server. You may only leave one or two of these
      # - 8853:8853/udp # add if you are going to run AdGuard Home as a DNS-over-QUIC server. You may only leave one or two of these
      # - 5443:5443/tcp # add if you are going to run AdGuard Home as a DNSCrypt server
      # - 5443:5443/udp # add if you are going to run AdGuard Home as a DNSCrypt server
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.adguardhome.middlewares: localaccess@file
      traefik.http.services.adguardhome.loadbalancer.server.port: 3000
      homepage.group: Infra
      homepage.name: AdGuard Home
      homepage.icon: adguard-home.png
      homepage.href: https://adguardhome.${MYDOMAIN}/
      homepage.description: Blocking ads and tracking
      homepage.widget.type: adguard
      homepage.widget.url: https://adguardhome.${MYDOMAIN}
      homepage.widget.username: ${ADMIN_USER}
      homepage.widget.password: ${ADMIN_PASSWORD}

networks:
  proxy:
    external: true
