# Syncthing replaces proprietary sync and cloud services with something open, trustworthy and decentralized.
# Your data is your data alone and you deserve to choose where it is stored, if it is shared with some third party and how it's transmitted over the Internet.
#
# 🏠 Home: https://syncthing.net/  
# 📦 Image: https://hub.docker.com/r/linuxserver/syncthing  
---
name: syncthing
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    restart: unless-stopped
    hostname: nest
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - ${DOCKER_VOLUMES}/syncthing:/config
      - ${STORAGE_SYNCTHING}:/storage
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.syncthing.entrypoints: websecure
      traefik.http.routers.syncthing.middlewares: https-local-auth@file
      traefik.http.services.syncthing.loadbalancer.server.port: 8384
      homepage.group: Storage
      homepage.name: Syncthing
      homepage.icon: syncthing.png
      homepage.href: https://syncthing.${MYDOMAIN}/
      homepage.description: "[SSO] File Sync" # TODO solve double auth

networks:
  proxy:
    external: true
