name: ddclient
services:
  # Replaces environment variables in config files before ddclient starts.
  initContainer:
    build:
      context: .
      dockerfile: Dockerfile.envsubst
    image: local/ddclient-envsubst:latest
    environment:
      CLOUDFLARE_DNS_API_TOKEN: ${CLOUDFLARE_DNS_API_TOKEN}
      MYDOMAIN: ${MYDOMAIN}
    container_name: ddclient-init
    volumes:
      - ./config:/workdir
      - ${DOCKER_VOLUMES}/ddclient:/processed

  ddclient:
    image: lscr.io/linuxserver/ddclient:4.0.0
    container_name: ddclient
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - ${DOCKER_VOLUMES}/ddclient:/config
    restart: unless-stopped
    depends_on:
      initContainer:
        condition: service_completed_successfully
    labels:
      homepage.group: Tools
      homepage.name: ddclient
      homepage.icon: cloudflare.png
      homepage.href: https://dash.cloudflare.com/
      homepage.description: Dynamic DNS updater
