# Encrypted, Compressed, and Deduplicated Backups Using the Cloud Storage You Pick
# Cross-platform backup tool for Windows, macOS & Linux with fast, incremental backups, client-side end-to-end encryption, compression and data deduplication. CLI and GUI included.
#
# https://kopia.io/
# https://github.com/kopia/kopia
# https://github.com/kopia/kopia/tree/master/tools/docker
---
version: "3.5"
name: kopia
services:
  kopia:
    image: kopia/kopia:latest
    container_name: kopia
    restart: "unless-stopped"
    user: "0:0"
    privileged: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    command:
      - server
      - start
      - --disable-csrf-token-checks
      - --insecure
      - --address=0.0.0.0:80
      - --server-username=${ADMIN_USER}
      - --server-password=${ADMIN_PASSWORD}
    environment:
      USER: ${ADMIN_USER}
      KOPIA_PASSWORD: ${ADMIN_PASSWORD}
      TZ: ${TIMEZONE}
    volumes:
      #- /mnt/kopia:/tmp:shared
      - ${DOCKER_VOLUMES}/kopia/config:/app/config
      - ${DOCKER_VOLUMES}/kopia/cache:/app/cache
      - ${DOCKER_VOLUMES}/kopia/logs:/app/logs
      - /:/local-data:ro
      - /home/buba/backup:/local-repo
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.kopia.entrypoints: websecure
      traefik.http.routers.kopia.middlewares: local-ipwhitelist@file
      traefik.http.services.kopia.loadbalancer.server.port: 80
      homepage.group: Storage
      homepage.name: Kopia - Local
      homepage.icon: kopia.png
      homepage.href: https://kopia.${MYDOMAIN}/
      homepage.description: Backups Using the Cloud Storage You Pick

networks:
  proxy:
    external: true
