# Encrypted, Compressed, and Deduplicated Backups Using the Cloud Storage You Pick
# Cross-platform backup tool for Windows, macOS & Linux with fast, incremental backups, client-side end-to-end encryption, compression and data deduplication. CLI and GUI included.
#
# https://kopia.io/
# https://github.com/kopia/kopia
# https://github.com/kopia/kopia/tree/master/tools/docker
---
services:
  kopia-b2:
    image: kopia/kopia:latest
    container_name: kopia-b2
    restart: "unless-stopped"
    user: "0:0"
    privileged: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    command:
      - server
      - start
      - --disable-csrf-token-checks
      - --insecure
      - --address=0.0.0.0:80
      - --server-username=${ADMIN_USER}
      - --server-password=${ADMIN_PASSWORD}
    environment:
      USER: ${ADMIN_USER}
      KOPIA_PASSWORD: ${KOPIA_B2_REPOSOTORY_PASSWORD}
      TZ: $TIMEZONE
    volumes:
      - ${CONTAINERDATA}/kopia-b2/config:/app/config
      - ${CONTAINERDATA}/kopia-b2/cache:/app/cache
      - ${CONTAINERDATA}/kopia-b2/logs:/app/logs
      - /mnt/nas/family-media:/mnt/family-media:ro
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.kopia-b2.entrypoints=websecure
      - traefik.http.routers.kopia-b2.rule=Host(`kopia-b2.${MYDOMAIN}`)
      - traefik.http.services.kopia-b2.loadbalancer.server.port=80

networks:
  proxy:
    external: true
