# Hard Drive S.M.A.R.T Monitoring, Historical Trends & Real World Failure Thresholds
#
# https://github.com/AnalogJ/scrutiny
#
# In addition to the Omnibus image (available under the latest tag) you can deploy in Hub/Spoke mode
# https://github.com/AnalogJ/scrutiny/blob/master/docker/example.hubspoke.docker-compose.yml
---
version: "3.5"
name: scrutiny
services:
  scrutiny-influxdb:
    image: influxdb:2.2
    container_name: scrutiny-influxdb
    restart: unless-stopped
    ports:
      - 8086:8086
    volumes:
      - ${DOCKER_VOLUMES}/scrutiny/influxdb:/var/lib/influxdb2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 15s
      timeout: 10s
      retries: 20

  scrutiny-web:
    image: 'ghcr.io/analogj/scrutiny:master-web'
    container_name: scrutiny-web
    restart: unless-stopped
    ports:
      - 8085:8080
    volumes:
      - ${DOCKER_VOLUMES}/scrutiny/config:/opt/scrutiny/config
    environment:
      SCRUTINY_WEB_INFLUXDB_HOST: 'scrutiny-influxdb'
    depends_on:
      scrutiny-influxdb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 15s
      timeout: 10s
      retries: 20
      start_period: 10s
    labels:
      homepage.group: Storage
      homepage.name: Scrutiny
      homepage.icon: scrutiny.png
      homepage.href: https://scrutiny.${MYDOMAIN}/
      homepage.description: Hard Drive S.M.A.R.T Monitoring

  scrutiny-collector:
    image: 'ghcr.io/analogj/scrutiny:master-collector'
    container_name: scrutiny-collector
    restart: unless-stopped
    cap_add:
      - SYS_RAWIO
    volumes:
      - /run/udev:/run/udev:ro
    environment:
      COLLECTOR_API_ENDPOINT: 'http://localhost:8080'
      COLLECTOR_CRON_SCHEDULE: '0 0 * * *'
    depends_on:
      scrutiny-web:
        condition: service_healthy
    devices:
      - /dev/sda
      #- /dev/sdb
