# Syncthing replaces proprietary sync and cloud services with something open, trustworthy and decentralized. Your data is your data alone and you deserve to choose where it is stored, if it is shared with some third party and how it's transmitted over the Internet.
#
# https://hub.docker.com/r/linuxserver/syncthing
---
version: "3.5"
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    restart: unless-stopped
    hostname: nest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${DOCKER_VOLUMES}/syncthing:/config
      - ${ALLSTORAGE}:/storage
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
