# Encrypted, Compressed, and Deduplicated Backups Using the Cloud Storage You Pick
# Cross-platform backup tool for Windows, macOS & Linux with fast, incremental backups, client-side end-to-end encryption, compression and data deduplication. CLI and GUI included.
#
# https://kopia.io/
# https://github.com/kopia/kopia
# https://github.com/kopia/kopia/tree/master/tools/docker
---
version: "3.5"
name: kopia-b2
services:
  kopia-b2:
    image: kopia/kopia:latest
    container_name: kopia-b2
    restart: "unless-stopped"
    user: "0:0"
    privileged: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    command:
      - server
      - start
      - --disable-csrf-token-checks
      - --insecure
      - --without-password
      - --address=0.0.0.0:80
    environment:
      USER: ${ADMIN_USER}
      KOPIA_PASSWORD: ${KOPIA_B2_REPOSOTORY_PASSWORD}
      TZ: ${TIMEZONE}

    volumes:
      - ${DOCKER_VOLUMES}/kopia-b2/config:/app/config
      - ${DOCKER_VOLUMES}/kopia-b2/cache:/app/cache
      - ${DOCKER_VOLUMES}/kopia-b2/logs:/app/logs

      # Nest (source)
      - /etc:/sources/nest/etc:ro
      - ${DOCKER_VOLUMES}:/sources/nest/docker-volumes:ro
      - ${ADMIN_HOME}/repos:/sources/nest/repos:ro
      - ${STORAGE_NEST_MEDIA}:/sources/nest/media:ro

      # NAS (source)
      - ${FAMILYMEDIA}:/sources/nas/family-media:ro
      - ${MEDIA}:/sources/nas/media:ro

    networks:
      - proxy

    labels:
      traefik.enable: true
      traefik.http.routers.kopia-b2.entrypoints: websecure
      traefik.http.routers.kopia-b2.middlewares: https-local-auth@file
      traefik.http.services.kopia-b2.loadbalancer.server.port: 80
      homepage.group: Storage
      homepage.name: Kopia - Backblaze B2
      homepage.icon: kopia.png
      homepage.href: https://kopia-b2.${MYDOMAIN}/
      homepage.description: "[SSO] Backups Using the Cloud Storage You Pick"

networks:
  proxy:
    external: true
