name: mongodb
services:
  mongodb-init:
    image: busybox:1.38.0
    container_name: mongodb-init
    command: ["sh", "-c", "chown -R 999:999 /data/db"]
    volumes:
      - ${DOCKER_VOLUMES}/mongodb/data:/data/db

  mongodb:
    image: mongo:7.0.43-jammy
    container_name: mongodb
    restart: unless-stopped
    # kics-scan ignore-block
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:?MongoDB root password must be set}
    volumes:
      - ${DOCKER_VOLUMES}/mongodb/data:/data/db
      - ./config/initdb:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017
    networks:
      - proxy
    depends_on:
      mongodb-init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      traefik.enable: false
      homepage.group: Storage
      homepage.name: MongoDB
      homepage.icon: mongodb.png
      homepage.description: "Popular NoSQL document database"

networks:
  proxy:
    external: true
