# https://hub.docker.com/r/linuxserver/plex
---
version: "3.5"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      #- PLEX_CLAIM= #optional
    volumes:
      - /path/to/library:/config
      - ${MEDIA}:/media
      #- /path/to/tvseries:/tv
      #- /path/to/movies:/movies
    restart: unless-stopped
