# https://brew.sh/
# https://docs.brew.sh/Homebrew-on-Linux
---
- name: Check if Homebrew is installed (on Linux)
  ansible.builtin.stat:
    path: /home/linuxbrew/.linuxbrew/bin/brew
  register: homebrew_check_linux
  when: ansible_system == "Linux"

- name: Check if Homebrew is installed (on Darwin)
  ansible.builtin.stat:
    path: /opt/homebrew/bin/brew
  register: homebrew_check_darwin
  when: ansible_system == "Darwin"

# Not yet installed -> install
- name: Install Homebrew
  ansible.builtin.shell: /bin/bash -c "NONINTERACTIVE=true $(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  become: false
  when: not ((homebrew_check_linux.stat is defined and homebrew_check_linux.stat.exists) or (homebrew_check_darwin.stat is defined and homebrew_check_darwin.stat.exists))

# Already installed -> update
- name: Update Homebrew
  community.general.homebrew:
    update_homebrew: true
  when: (homebrew_check_linux.stat is defined and homebrew_check_linux.stat.exists) or (homebrew_check_darwin.stat is defined and homebrew_check_darwin.stat.exists)
  become: false

# TODO configure for user (on Linux)
# test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
# test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
# echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >> ~/.bashrc

- name: Install Homebrew packages
  community.general.homebrew:
    # name: "{{ brew_base_tools + brew_cloud_tools + brew_terraform_tools + brew_kubernetes_tools }}"
    name: "{{ dev_brew_packages }}"
    state: present
  become: false
  when:
    - dev_brew_packages is defined
    - dev_brew_packages | type_debug == 'list'
    - dev_brew_packages | length > 0

- name: Install Homebrew Cask packages (only on Darwin)
  community.general.homebrew_cask:
    name: "{{ dev_brew_cask_packages }}"
    state: present
  become: false
  when:
    - ansible_system == "Darwin"
    - dev_brew_cask_packages is defined
    - dev_brew_cask_packages | type_debug == 'list'
    - dev_brew_cask_packages | length > 0
