---
- name: Install packages with apt
  ansible.builtin.import_tasks: 10-apt.yaml

# https://brew.sh/
# https://docs.brew.sh/Homebrew-on-Linux
- name: Install packages with Homebrew
  ansible.builtin.include_tasks: 20-homebrew.yaml
  when:
    - dev_brew_packages is defined             or dev_brew_cask_packages is defined
    - dev_brew_packages | type_debug == 'list' or dev_brew_cask_packages | type_debug == 'list'
    - dev_brew_packages | length > 0           or dev_brew_cask_packages | length > 0
