# Portainer Community Edition is a lightweight service delivery platform for containerized applications that can be used to manage Docker, Swarm, Kubernetes and ACI environments.
# It is designed to be as simple to deploy as it is to use. The application allows you to manage all your orchestrator resources (containers, images, volumes, networks and more) through a ‘smart’ GUI and/or an extensive API.
#
# In order to generate an API key, please follow the steps outlined here: https://docs.portainer.io/api/access
#
# 🏠 Home: https://www.portainer.io/  
# 📜 Source: https://github.com/portainer/portainer  
---
name: portainer
services:
  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_VOLUMES}/portainer:/data
    ports:
      # Keep this as fallback if Traefik is not available
      - 9000:9000
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.portainer.entrypoints: websecure
      traefik.http.routers.portainer.middlewares: https-local@file
      traefik.http.services.portainer.loadbalancer.server.port: 9000
      homepage.group: Infra
      homepage.name: Portainer
      homepage.icon: portainer.png
      homepage.href: https://portainer.${MYDOMAIN}/
      homepage.description: Docker and Kubernetes management
      homepage.widget.type: portainer
      homepage.widget.url: https://portainer.${MYDOMAIN}
      homepage.widget.env: 2
      homepage.widget.key: ${PORTAINER_API_KEY}

networks:
  proxy:
    external: true
