# Encrypted, Compressed, and Deduplicated Backups Using the Cloud Storage You Pick
# Cross-platform backup tool for Windows, macOS & Linux with fast, incremental backups, client-side end-to-end encryption, compression and data deduplication. CLI and GUI included.
#
# https://kopia.io/
# https://github.com/kopia/kopia
# https://github.com/kopia/kopia/tree/master/tools/docker
---
version: "3.5"
name: kopia-nas
services:
  kopia-nas:
    image: kopia/kopia:latest
    container_name: kopia-nas
    restart: "unless-stopped"
    user: "0:0"
    privileged: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    command:
      - server
      - start
      - --disable-csrf-token-checks
      - --insecure
      - --without-password
      - --address=0.0.0.0:80
    environment:
      USER: ${ADMIN_USER}
      KOPIA_PASSWORD: ${KOPIA_NAS_REPOSOTORY_PASSWORD}
      TZ: ${TIMEZONE}

    volumes:
      - ${DOCKER_VOLUMES}/kopia-nas/config:/app/config
      - ${DOCKER_VOLUMES}/kopia-nas/cache:/app/cache
      - ${DOCKER_VOLUMES}/kopia-nas/logs:/app/logs

      # Nest (source)
      - /etc:/sources/nest/etc:ro
      - ${DOCKER_VOLUMES}:/sources/nest/docker-volumes:ro
      - ${HOME}/repos:/sources/nest/repos:ro

      # NAS (repository)
      - ${BACKUP_ON_NAS}/kopia:/backup-on-nas

    networks:
      - proxy

    labels:
      traefik.enable: true
      traefik.http.routers.kopia-nas.entrypoints: websecure
      traefik.http.routers.kopia-nas.middlewares: https-local-auth@file
      traefik.http.services.kopia-nas.loadbalancer.server.port: 80
      homepage.group: Storage
      homepage.name: Kopia - NAS
      homepage.icon: kopia.png
      homepage.href: https://kopia-nas.${MYDOMAIN}/
      homepage.description: "[SSO] Backups Using the Cloud Storage You Pick"

networks:
  proxy:
    external: true
