# Based on:
#   https://docs.docker.com/engine/install/debian/
---
- name: Install required system packages
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      - cgroupfs-mount # To solve the issue: Docker failed to start daemon - "Devices cgroup isn't mounted"
    state: present

- name: Add Docker GPG Key (on Debian)
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker Repository (on Debian)
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
    state: present

- name: Update apt and install docker-ce
  ansible.builtin.apt:
    name: docker-ce
    state: present
    update_cache: true

- name: Enable and start docker service
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started

- name: Install Docker Module for Python
  ansible.builtin.pip:
    name: docker
  environment:
    # For compatibility with PEP668 - https://forum.ansible.com/t/breaking-changes-with-pip-and-system-packages/2177
    PIP_BREAK_SYSTEM_PACKAGES: "1"
