filenames:
  - /var/log/auth.log
labels:
  type: syslog
---
filenames:
  - /var/log/traefik-access.log
labels:
  type: traefik
---
source: docker
docker_host: tcp://dockerproxy:2375
container_name:
  - authentik-server
labels:
  type: authentik
---
filenames:
  - /var/log/vaultwarden.log
labels:
  type: vaultwarden
---
filenames:
  - /var/log/jellyfin/log_*.log
labels:
  type: jellyfin
---
filenames:
  - /var/log/endlessh/*
labels:
  type: endlessh
