# Making Docker and Kubernetes management easy.
#
# https://github.com/portainer/portainer
---
version: "3.5"
services:
  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONTAINERDATA}/portainer:/data
    # ports:
    #   - 9000:9000
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.routers.portainer.rule=Host(`portainer.${MYDOMAIN}`)
      - traefik.http.services.portainer.loadbalancer.server.port=9000

networks:
  proxy:
    external: true
