# Making Docker and Kubernetes management easy.
#
# https://github.com/portainer/portainer
---
version: "3.5"
services:
  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONTAINERDATA}/portainer:/data
    ports:
      - 9000:9000
    restart: unless-stopped