FROM lscr.io/linuxserver/qbittorrent:4.6.5

WORKDIR /usr
RUN curl -LO https://github.com/WDaan/VueTorrent/releases/latest/download/vuetorrent.zip && \
    unzip vuetorrent.zip && \
    rm vuetorrent.zip
