FROM lscr.io/linuxserver/qbittorrent:latest

RUN cd /usr && \
    curl -LO https://github.com/WDaan/VueTorrent/releases/latest/download/vuetorrent.zip && \
    unzip vuetorrent.zip && \
    rm vuetorrent.zip
