---
ubuntu_desktop_snap_packages:
  - brave
  - steam

ubuntu_desktop_snap_classic_packages:
  - code

ubuntu_desktop_install_chrome: true

ubuntu_desktop_install_rustdesk: true
# renovate: datasource=github-releases depName=rustdesk/rustdesk
ubuntu_desktop_rustdesk_version: "1.5.0"

ubuntu_desktop_install_sunshine: false
# renovate: datasource=github-releases depName=LizardByte/Sunshine
ubuntu_desktop_sunshine_version: "2026.914.233613"
