# Navidrome is an open source web-based music collection server and streamer.
# It gives you freedom to listen to your music collection from any browser or mobile device.
#
# In case of "unable to open database file: no such file or directory" error, chown the `data` directory to match `${PUID}:${PGID}`.
#
# 🏠 Home: https://www.navidrome.org/  
# 📦 Image: https://hub.docker.com/r/deluan/navidrome  
# Installing with Docker: https://www.navidrome.org/docs/installation/docker/  
# Configuration Options: https://www.navidrome.org/docs/usage/configuration-options/  
#
# Recommended desktop player:  
# Sonixd - A full-featured Subsonic/Jellyfin compatible desktop music player  
# https://github.com/jeffvli/sonixd  
# (Fix startup issue Mac: `xattr -cr /Applications/Sonixd.app`)
---
name: navidrome
services:
  navidrome:
    image: deluan/navidrome:0.54.4
    container_name: navidrome
    user: ${PUID}:${PGID} # Should be owner of volumes
    restart: unless-stopped
    environment:
      # Put your config options customization here
      ND_SCANSCHEDULE: 8h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_MUSICFOLDER: /media/music
    volumes:
      - ${DOCKER_VOLUMES}/navidrome:/data
      - ${STORAGE_MEDIA}/music:/media/music:ro
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.navidrome.middlewares: localaccess@file
      traefik.http.services.navidrome.loadbalancer.server.port: 4533
      homepage.group: Media
      homepage.name: Navidrome
      homepage.icon: navidrome.png
      homepage.href: https://navidrome.${MYDOMAIN}/
      homepage.description: Music collection

networks:
  proxy:
    external: true
