---
###############################################################
#                   Authelia configuration                    #
###############################################################

server:
  address: tcp://0.0.0.0:9091/

log:
  level: info
  format: json
  file_path: "/data/authelia.log"
  keep_stdout: true

theme: dark

# 'identity_validation.reset_password.jwt_secret' is set via AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET

totp:
  issuer: authelia.com

# One-Tap Authentication With Duo Push
# https://duo.com/product/multi-factor-authentication-mfa/authentication-methods/duo-push
# duo_api:
#  hostname: api-123456789.example.com
#  integration_key: ABCDEF
#  secret_key: 1234567890abcdefghifjkl # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64

access_control:
  default_policy: deny
  rules:
    - domain: "auth.${MYDOMAIN}"
      policy: bypass
    # Two-factor example:
    # - domain: "very-secure.${MYDOMAIN}"
    #   policy: two_factor
    - domain: "*.${MYDOMAIN}"
      # subject:
      #   - "group:admins"
      policy: one_factor

session:
  # 'secret' is set via AUTHELIA_SESSION_SECRET
  name: 'authelia_session'
  same_site: 'lax'
  inactivity: '1h'
  expiration: '8h'
  remember_me: '1M'
  cookies:
    - domain: ${MYDOMAIN} # Should match whatever your root protected domain is
      authelia_url: 'https://auth.${MYDOMAIN}'
      default_redirection_url: 'https://home.${MYDOMAIN}'
      name: 'authelia_session'
      same_site: 'lax'
      inactivity: '1h'
      expiration: '8h'
      remember_me: '1M'

  # redis:
  #   host: redis
  #   port: 6379
  #   # password: authelia # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD

regulation:
  max_retries: 3
  find_time: 10m
  ban_time: 12h

storage:
  # 'encryption_key' is set via AUTHELIA_STORAGE_ENCRYPTION_KEY
  local:
    path: /data/db.sqlite3

notifier:
  # smtp:
  #   username: test
  #   # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD
  #   password: password
  #   host: mail.example.com
  #   port: 25
  #   sender: admin@example.com
  filesystem:
    filename: /data/notification.txt
