---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# Generate password hash with:
#   docker run authelia/authelia:latest authelia hash-password 'yourpassword'

# List of users
users:
  ${ADMIN_USER}:
    displayname: "${ADMIN_DISPLAYNAME}"
    password: "${AUTHELIA_ADMIN_PASSWORD}"
    email: "${ADMIN_EMAIL}"
    groups:
      - admins
      - dev
