name: autogenstudio
services:
  autogenstudio:
    build: .
    container_name: autogenstudio
    restart: unless-stopped
    volumes:
      - ${DOCKER_VOLUMES}/autogenstudio:/root/.autogenstudio
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.autogenstudio.middlewares: localaccess@file
      traefik.http.services.autogenstudio.loadbalancer.server.port: 8081
      homepage.group: AI
      homepage.name: AutoGen Studio
      homepage.icon: chatgpt.png
      homepage.href: https://autogenstudio.${MYDOMAIN}/
      homepage.description: "Rapidly prototype AI agents"
      com.centurylinklabs.watchtower.enable: false

networks:
  proxy:
    external: true
