# Filebrowser provides a file managing interface within a specified directory and it can be used to upload, delete, preview, rename and edit your files.
#
# Default credentials: `admin` / `admin`
#
# 🏠 Home: https://filebrowser.org/  
# 📜 Source: https://github.com/filebrowser/filebrowser  
---
name: filebrowser
services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - ${STORAGE_ALL}:/srv
      - ${DOCKER_VOLUMES}/filebrowser/filebrowser.db:/database/filebrowser.db
      - ${DOCKER_VOLUMES}/filebrowser/settings.json:/config/settings.json
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.filebrowser.middlewares: localaccess@file
      traefik.http.services.filebrowser.loadbalancer.server.port: 80
      homepage.group: Storage
      homepage.name: Filebrowser
      homepage.icon: filebrowser.png
      homepage.href: https://filebrowser.${MYDOMAIN}/
      homepage.description: File Management

networks:
  proxy:
    external: true
