# Syncthing replaces proprietary sync and cloud services with something open, trustworthy and decentralized.
# Your data is your data alone and you deserve to choose where it is stored, if it is shared with some third party and how it's transmitted over the Internet.
#
# 🏠 Home: https://syncthing.net/  
# 📦 Image: https://hub.docker.com/r/linuxserver/syncthing  
---
name: syncthing
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:1.29.2
    container_name: syncthing
    restart: unless-stopped
    network_mode: host
    hostname: ${MAIN_NODE}
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - ${DOCKER_VOLUMES}/syncthing:/config
      - ${STORAGE_SYNCTHING}:/storage
    # Not needed due to 'network_mode: host'
    # ports:
    #   - 22000:22000/tcp
    #   - 22000:22000/udp
    #   - 21027:21027/udp
    labels:
      traefik.enable: true
      traefik.http.routers.syncthing.middlewares: localaccess-sso@file
      traefik.http.services.syncthing.loadbalancer.server.port: 8384
      homepage.group: Storage
      homepage.name: Syncthing
      homepage.icon: syncthing.png
      homepage.href: https://syncthing.${MYDOMAIN}/
      homepage.description: "[SSO] File Sync" # TODO solve double auth
