---
- name: Configure network
  hosts: all
  become: true

  tasks:
    - name: Add IP address of all hosts to all hosts
      ansible.builtin.lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item }}$'
        line: "{{ hostvars[item].ansible_host }} {{ item }}"
        state: present
      when: hostvars[item].ansible_host is defined
      with_items: "{{ groups.all }}"

    # https://www.linuxuprising.com/2020/07/ubuntu-how-to-free-up-port-53-used-by.html
    - name: Disable DNSStubListener
      ansible.builtin.lineinfile:
        path: /etc/systemd/resolved.conf
        regexp: '^(.*)DNSStubListener(.*)$'
        line: 'DNSStubListener=no'
        backrefs: true
      notify: Restart service systemd-resolved

    - name: Create symbolic link to resolv.conf
      ansible.builtin.file:
        src: /run/systemd/resolve/resolv.conf
        dest: /etc/resolv.conf
        owner: systemd-resolve
        group: systemd-resolve
        state: link

  handlers:
    - name: Restart service systemd-resolved
      ansible.builtin.service:
        name: systemd-resolved
        state: restarted
