version: '3'

env:
  OBSIDIAN_VAULT_NAME: ".."

tasks:
  # Note: to avoid syncing the .git folder by Obsidian, .git folder is placed outside of the Vault
  # Reference: https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---separate-git-dirgit-dir
  # Clone command: `git clone --separate-git-dir`
  push-vault-repo:
    desc: Run improvement tasks on the Obsidian Vault git repository, commit and push changes
    env:
      STORAGE_OBSIDIAN:
        sh: |
          set -a
          source config/docker/.env
          source config/docker/localhost/.env
          echo "$STORAGE_OBSIDIAN"
    silent: true
    cmds:
      - |
        VAULT_PATH="${STORAGE_OBSIDIAN}/${OBSIDIAN_VAULT_NAME}/"
        cd "${VAULT_PATH}" || { echo "Failed to cd to '${VAULT_PATH}'"; exit 1; }
        task improve

  stop-obsidian:
    desc: Stop Obsidian service
    cmds:
      - scripts/labctl.py service down tools/obsidian

  start-obsidian:
    desc: Start Obsidian service
    cmds:
      - scripts/labctl.py service up tools/obsidian

  backup-vault-repo:
    desc: Stop Obsidian, commit and push changes to git, then start the service
    cmds:
      - task: stop-obsidian
      - defer: { task: start-obsidian }
      - task: push-vault-repo
