# Client for Cloudflare Tunnel, a daemon that exposes private services through the Cloudflare edge.
#
# 🏠 Home: https://www.cloudflare.com/products/tunnel/  
# 📦 Image: https://hub.docker.com/r/cloudflare/cloudflared  
# Introduction: https://www.crosstalksolutions.com/cloudflare-tunnel-easy-setup/  
---
name: cloudflared
services:
  cloudflared:
    image: cloudflare/cloudflared:2025.2.0
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - proxy
    labels:
      homepage.group: Security
      homepage.name: Cloudflared
      homepage.icon: cloudflare.png
      homepage.href: https://dash.cloudflare.com/
      homepage.description: "Cloudflare Tunnel"

networks:
  proxy:
    external: true
