global:
  scrape_interval: 60s # By default, scrape targets every 60 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # external_labels:
  #  monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    scrape_interval: 120s
    static_configs:
      - targets:
          - 'localhost:9090' # Main node

  - job_name: 'node_exporter'
    static_configs:
      - targets:
          - 'node_exporter:9100' # Main node
          - '192.168.1.10:9100'  # "NAS" host

  - job_name: 'cadvisor'
    static_configs:
      - targets:
          - 'cadvisor:8080' # Main node

  - job_name: 'endlessh'
    static_configs:
      - targets:
          - 'endlessh:2112' # Main node
