[project]
name = "task-mcp"
version = "0.1.0"
description = "MCP server for task runner integration"
requires-python = ">=3.10"
dependencies = [
    "fastmcp>=2.10.0",
]

[project.scripts]
task-mcp = "server:main"
