# Grafana open source software enables you to query, visualize, alert on, and explore your metrics, logs, and traces wherever they are stored.
# Grafana OSS provides you with tools to turn your time-series database (TSDB) data into insightful graphs and visualizations.
# The Grafana OSS plugin framework also enables you to connect other data sources like NoSQL/SQL databases, ticketing tools like Jira or ServiceNow, and CI/CD tooling like GitLab.
# ([source](https://grafana.com/docs/grafana/latest/introduction/))
#
# Default admin user credentials: `admin` / `admin`
#
# 🏠 Home: https://grafana.com/grafana/  
# 📦 Image: https://hub.docker.com/r/grafana/grafana-oss  
# Getting Started: https://grafana.com/docs/grafana/latest/getting-started/getting-started/  
# New in v12: https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v12-0/
#
# Recommended dashboards to import:
# - https://grafana.com/grafana/dashboards/1860-node-exporter-full/
# - https://grafana.com/grafana/dashboards/14282-cadvisor-exporter/
---
name: grafana
services:
  grafana:
    image: grafana/grafana-oss:12.0.1
    container_name: grafana
    restart: unless-stopped
    user: "0:0"
    volumes:
      - ${DOCKER_VOLUMES}/grafana:/var/lib/grafana
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.grafana.middlewares: localaccess@file
      traefik.http.services.grafana.loadbalancer.server.port: 3000
      homepage.group: Monitoring
      homepage.name: Grafana
      homepage.icon: grafana.png
      homepage.href: https://grafana.${MYDOMAIN}/
      homepage.description: "Monitoring dashboard"

networks:
  proxy:
    external: true

# volumes:
#   grafana-data:
#     driver: local
