# Prometheus exporter for machine metrics, written in Go with pluggable metric collectors.
#
# 📜 Source: https://github.com/prometheus/node_exporter  
# 📦 Image: https://hub.docker.com/r/prom/node-exporter/  
---
name: node_exporter
services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.9.0
    container_name: node_exporter
    restart: unless-stopped
    pid: host
    ports:
      - 9100:9100
    command:
      - '--path.rootfs=/host'
    # kics-scan ignore-block
    volumes:
      - '/:/host:ro,rslave'
