# Web GUI for youtube-dl (using the yt-dlp fork) with playlist support. Allows you to download videos from YouTube and dozens of other sites
#
# 📜 Source: https://github.com/alexta69/metube  
# Supported sites: https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md  
---
version: "3.5"
name: metube
services:
  metube:
    image: alexta69/metube
    container_name: metube
    restart: "unless-stopped"
    environment:
      UID: ${PUID}
      GID: ${PGID}
    volumes:
      - ${STORAGE_DOWNLOADS}/youtube:/downloads
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.metube.entrypoints: websecure
      traefik.http.routers.metube.middlewares: https-local@file
      traefik.http.services.metube.loadbalancer.server.port: 8081
      homepage.group: Media
      homepage.name: Metube
      homepage.icon: metube.png
      homepage.href: https://metube.${MYDOMAIN}/
      homepage.description: Video downloader

networks:
  proxy:
    external: true
