name: homeassistant
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:2026.9.2
    container_name: homeassistant
    restart: unless-stopped
    network_mode: host
    hostname: ${PRIMARY_NODE}
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - ${DOCKER_VOLUMES}/homeassistant:/config
    expose:
      - 8123 # Web UI
    # devices:
    #   - /path/to/device:/path/to/device  # optional
    labels:
      traefik.enable: true
      traefik.http.routers.homeassistant.middlewares: localaccess@file
      traefik.http.routers.homeassistant.rule: Host(`ha.${MYDOMAIN}`)
      traefik.http.services.homeassistant.loadbalancer.server.port: 8123
      homepage.group: Automation
      homepage.name: HomeAssistant
      homepage.icon: home-assistant.png
      homepage.href: https://ha.${MYDOMAIN}/
      homepage.description: Open source home automation
