# yaml-language-server: $schema=https://json.schemastore.org/traefik-v3.json

# Dynamic configuration - changes in this file are applied without restarting Traefik (https://doc.traefik.io/traefik/providers/file/#watch).
# Configuration via environment variables: use go templating, like {{env "VARIABLENAME"}}

http:

  # Allow self-signed certificates for proxied web services
  serversTransports:
    insecureTransport:
      insecureSkipVerify: true

  ## MIDDLEWARES ##
  middlewares:
    localaccess:
      chain:
        middlewares:
          - local-ip-allowlist

    localaccess-sso:
      chain:
        middlewares:
          - local-ip-allowlist
          - authelia

    publicaccess:
      chain:
        middlewares:
          - crowdsec-bouncer
          # - security-headers

    https-only:
      redirectScheme:
        scheme: https

    # Allow only local networks
    local-ip-allowlist:
      ipAllowList:
        sourceRange:
          - 127.0.0.1/32    # localhost
          - 10.0.0.0/8      # private class A
          - 172.16.0.0/12   # private class B
          - 192.168.0.0/16  # private class C

    authelia:
      forwardAuth:
        address: 'http://authelia:9091/api/verify?rd=https://auth.{{env "MYDOMAIN"}}'
        authResponseHeaders: Remote-User,Remote-Groups,Remote-Name,Remote-Email
        trustForwardHeader: true

    crowdsec-bouncer:
      forwardAuth:
        address: http://bouncer-traefik:8080/api/v1/forwardAuth
        trustForwardHeader: true

    security-headers:
      headers:
        customResponseHeaders: # field names are case-insensitive
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
          Server: "" # prevent version disclosure
          X-Powered-By: "" # prevent version disclosure
          X-Forwarded-Proto: "https"
        sslProxyHeaders:
          X-Forwarded-Proto: "https"
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        contentTypeNosniff: true # X-Content-Type-Options
        customFrameOptionsValue: "SAMEORIGIN" # X-Frame-Options
        browserXssFilter: false # X-XSS-Protection; deprecated
        referrerPolicy: "strict-origin-when-cross-origin" # Referrer-Policy
        forceSTSHeader: true # HTTP-Strict-Transport-Security (HSTS)
        stsIncludeSubdomains: true # HTTP-Strict-Transport-Security (HSTS)
        stsSeconds: 63072000 # HTTP-Strict-Transport-Security (HSTS)
        stsPreload: true # HTTP-Strict-Transport-Security (HSTS)
        # contentSecurityPolicy: "block-all-mixed-content" # Content-Security-Policy (CSP)


# Only use secure ciphers
# Generated with Mozilla SSL Configuration Generator
# https://ssl-config.mozilla.org/#server=traefik&version=3.2.1&config=intermediate&guideline=5.7
tls:
  options:
    default:
      minVersion: VersionTLS12
      curvePreferences:
        - X25519
        - CurveP256
        - CurveP384
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
