# Making Docker and Kubernetes management easy
#
# https://github.com/portainer/portainer
---
version: "3.5"
name: portainer-agent
services:
  agent:
    image: portainer/agent:2.16.2
    container_name: portainer-agent
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    restart: always
