# yaml-language-server: $schema=https://json.schemastore.org/traefik-v3.json

# Issue one ACME certificate for the base domain and all first-level subdomains.
tls:
  stores:
    default:
      defaultGeneratedCert:
        resolver: letsencrypt
        domain:
          main: '{{env "MYDOMAIN"}}'
          sans:
            - '*.{{env "MYDOMAIN"}}'
