# Based on https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-22-04
---
- name: Install Docker
  hosts: all
  become: true

  tasks:
    - name: Install required system packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: present
        update_cache: false

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ ubuntu_version }} stable
        state: present

    - name: Update apt and install docker-ce
      ansible.builtin.apt:
        name: docker-ce
        state: present
        update_cache: true

    - name: Install Docker Module for Python
      ansible.builtin.pip:
        name: docker

    - name: Create docker-volumes directories
      ansible.builtin.file:
        path: /srv/docker-volumes
        state: directory
        owner: root
        group: root
        mode: '0777'

    # docker network create proxy
    - name: Create 'proxy' Docker network
      community.docker.docker_network:
        name: proxy

    # usermod -aG docker $USER
    - name: Add user admin_user to Docker group
      ansible.builtin.user:
        name: '{{ admin_user }}'
        groups: docker
        append: true
