#!/usr/bin/env ansible-playbook

- name: Setup Debian base
  become: true
  hosts:
    - azure-vm
  roles:
    - role: debian-base
    - role: debian-docker-host
    - role: markosamuli.linuxbrew
    - role: debian-developer
