#!/usr/bin/env ansible-playbook

- name: Setup Debian base
  hosts:
    - azure-vm
  roles:
    - role: debian_base
    - role: debian_docker_host
    - role: markosamuli.linuxbrew
    - role: debian_developer
