#!/usr/bin/env ansible-playbook

- name: Setup Debian base
  hosts:
    - debian
  roles:
    - role: debian_base

- name: Setup Docker-host
  hosts:
    - docker_hosts
  roles:
    - role: debian_docker_host

- name: Setup Debian tools
  hosts:
    - debian_tools_hosts
  roles:
    - role: debian_tools

- name: Setup Samba client
  hosts:
    - debian_samba_client_hosts
  roles:
    - role: debian_samba_client

- name: Setup Ubuntu desktop software
  hosts:
    - ubuntu_desktop_hosts
  roles:
    - role: ubuntu_desktop
