# Endlessh is an SSH tarpit that very slowly sends an endless, random SSH banner. It keeps SSH clients locked up for hours or even days at a time.
# The purpose is to put your real SSH server on another port and then let the script kiddies get stuck in this tarpit instead of bothering a real server.
#
# 📜 Source: https://github.com/skeeto/endlessh  
# Setup: https://docs.linuxserver.io/images/docker-endlessh/#application-setup  
---
name: endlessh
services:
  endlessh:
    image: lscr.io/linuxserver/endlessh:latest # No semantic version tags are available
    container_name: endlessh
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
      MSDELAY: 10000
      MAXLINES: 32
      MAXCLIENTS: 4096
      LOGFILE: true # /config/logs/endlessh/
      BINDFAMILY:
    volumes:
      - ${DOCKER_VOLUMES}/endlessh:/config
    ports:
      - 2222:2222
    labels:
      homepage.group: Security
      homepage.name: Endlessh
      homepage.icon: terminal.png
      homepage.description: "SSH tarpit (port 2222)"
