version: '3'

tasks:
  collections:
    desc: CrowdSec - List collection(s)
    cmds:
      - docker exec crowdsec cscli collections list

  bouncers:
    desc: CrowdSec - List all bouncers within the database
    cmds:
      - docker exec crowdsec cscli bouncers list

  decisions:
    desc: CrowdSec - List decisions from LAPI
    cmds:
      - docker exec crowdsec cscli decisions list

  alerts:
    desc: CrowdSec - List alerts
    cmds:
      - docker exec crowdsec cscli alerts list

  metrics:
    desc: CrowdSec - Fetch metrics from the prometheus server
    cmds:
      - docker exec crowdsec cscli metrics

  stats:
    desc: CrowdSec - Show all statistics
    cmds:
      - docker exec crowdsec cscli collections list
      - docker exec crowdsec cscli bouncers list
      - docker exec crowdsec cscli decisions list
      - docker exec crowdsec cscli alerts list
      - docker exec crowdsec cscli metrics
