title: HomeLab
languageCode: en-us
publishDir: ../public
uglyURLs: false

module:
  imports:
    - path: github.com/McShelby/hugo-theme-relearn

params:
  # themeVariant: "zen-dark"
  alwaysopen: "" # If not set, the first menu level is set to false, all others levels are set to true
  collapsibleMenu: true

  themeVariant:
    - auto: []
      identifier: relearn-auto
      name: Relearn Light/Dark
    - identifier: relearn-light
    - identifier: relearn-dark
    - identifier: relearn-bright
    - auto:
        - zen-light
        - zen-dark
      identifier: zen-auto
      name: Zen Light/Dark
    - identifier: zen-light
    - identifier: zen-dark
    - auto:
        - learn
        - neon
      identifier: retro-auto
      name: Retro Learn/Neon
    - identifier: neon
    - identifier: learn
    - identifier: blue
    - identifier: green
    - identifier: red

outputFormats:
  html:
    mediaType: text/html
