name: webdav
services:
  webdav:
    image: dgraziotin/nginx-webdav-nononsense:1.31.4
    container_name: webdav
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
      WEBDAV_USERNAME: ${ADMIN_USER}
      WEBDAV_PASSWORD: ${ADMIN_PASSWORD}
      SERVER_NAMES: webdav.${MYDOMAIN}
      TIMEOUTS_S: 1200 # these are seconds
      CLIENT_MAX_BODY_SIZE: 100M # must end with M(egabytes) or G(igabytes)
    volumes:
      - ${STORAGE_WEBDAV}:/data
      - ${ADMIN_HOME}/repos/infra:/data/Infra # 'infra' git repository
      - ${DOCKER_VOLUMES}/webdav/log:/var/log/nginx # error.log, access.log
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.webdav.middlewares: localaccess@file
      traefik.http.services.webdav.loadbalancer.server.port: 80
      homepage.group: Storage
      homepage.name: WebDAV
      homepage.icon: nginx.png
      homepage.href: https://webdav.${MYDOMAIN}/
      homepage.description: Nginx WebDAV Server

networks:
  proxy:
    external: true
