# Apache Guacamole is a clientless remote desktop gateway. It supports standard protocols like VNC and RDP. We call it clientless because no plugins or client software are required.
# Thanks to HTML5, once Guacamole is installed on a server, all you need to access your desktops is a web browser.
# The default username is guacadmin with password guacadmin.
#
# https://guacamole.apache.org/
# https://hub.docker.com/r/guacamole/guacamole
# https://hub.docker.com/r/maxwaldorf/guacamole
---
version: "3.5"
name: guacamole
services:
  guacamole:
    image: maxwaldorf/guacamole
    container_name: guacamole
    restart: unless-stopped
    environment:
      EXTENSIONS: auth-header
    volumes:
      - ${DOCKER_VOLUMES}/guacamole:/config
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.guacamole.entrypoints: websecure
      traefik.http.routers.guacamole.middlewares: https-local@file
      traefik.http.services.guacamole.loadbalancer.server.port: 8080
      homepage.group: Connections
      homepage.name: Guacamole
      homepage.icon: guacamole.png
      homepage.href: https://guacamole.${MYDOMAIN}/
      homepage.description: "Remote desktop gateway"

networks:
  proxy:
    external: true
