# SpeedTest by OpenSpeedTest™ is a Free and Open-Source HTML5 Network Performance Estimation Tool
#
# 📦 Image: https://hub.docker.com/r/openspeedtest/latest  
---
version: "3.5"
name: openspeedtest
services:
  openspeedtest:
    image: openspeedtest/latest:latest
    container_name: openspeedtest
    restart: unless-stopped
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.openspeedtest.middlewares: https-local@file
      traefik.http.services.openspeedtest.loadbalancer.server.port: 3000
      homepage.group: Tools
      homepage.name: OpenSpeedTest
      homepage.icon: librespeed.png # 404: openspeedtest.png
      homepage.href: https://openspeedtest.${MYDOMAIN}/
      homepage.description: "Network Performance Estimation"

networks:
  proxy:
    external: true
