# SSH key pair — ED25519 key generated by Terraform, registered with AWS
resource "tls_private_key" "main" {
  algorithm = "ED25519"
}

module "key_pair" {
  source  = "terraform-aws-modules/key-pair/aws"
  version = "~> 2.0"

  key_name   = var.vm_name
  public_key = tls_private_key.main.public_key_openssh

  tags = {
    Name = var.vm_name
  }
}

# VPC with a single public subnet — Internet Gateway is created automatically
module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "~> 5.0"

  name = var.vm_name
  cidr = "10.0.0.0/16"

  azs            = [data.aws_availability_zones.available.names[0]]
  public_subnets = ["10.0.1.0/24"]

  enable_dns_hostnames = true
  enable_dns_support   = true

  tags = {
    Name = var.vm_name
  }
}

# Security group: SSH and HTTPS from admin IP only, unrestricted egress
module "security_group" {
  source  = "terraform-aws-modules/security-group/aws"
  version = "~> 5.0"

  name        = "${var.vm_name}-sg"
  description = "Allow SSH and HTTPS from admin source"
  vpc_id      = module.vpc.vpc_id

  ingress_with_cidr_blocks = [
    {
      from_port   = 22
      to_port     = 22
      protocol    = "tcp"
      description = "SSH from admin"
      cidr_blocks = local.admin_cidr
    },
    {
      from_port   = 443
      to_port     = 443
      protocol    = "tcp"
      description = "HTTPS from admin"
      cidr_blocks = local.admin_cidr
    }
  ]

  egress_rules = ["all-all"]

  tags = {
    Name = "${var.vm_name}-sg"
  }
}

# EC2 instance
module "ec2" {
  source  = "terraform-aws-modules/ec2-instance/aws"
  version = "~> 5.0"

  name          = var.vm_name
  ami           = data.aws_ami.ubuntu.id
  instance_type = local.instance_type
  key_name      = module.key_pair.key_pair_name

  subnet_id                   = module.vpc.public_subnets[0]
  vpc_security_group_ids      = [module.security_group.security_group_id]
  associate_public_ip_address = true

  iam_instance_profile = aws_iam_instance_profile.ec2.name

  user_data_base64            = local.user_data
  user_data_replace_on_change = false

  root_block_device = [
    {
      volume_size           = var.os_disk_size_gb
      volume_type           = "gp3"
      encrypted             = true
      delete_on_termination = true
    }
  ]

  tags = {
    Name         = var.vm_name
    Architecture = var.architecture
  }
}

# Persistent data volume — survives instance termination
# NOTE: prevent_destroy = true means 'terraform destroy' will fail.
#       To fully destroy, remove this lifecycle block and re-apply first,
#       or delete the volume manually via the AWS Console / CLI.
resource "aws_ebs_volume" "data" {
  availability_zone = data.aws_availability_zones.available.names[0]
  size              = var.data_disk_size_gb
  type              = "gp3"
  encrypted         = true

  lifecycle {
    prevent_destroy = true
  }

  tags = {
    Name = "${var.vm_name}-data"
  }
}

resource "aws_volume_attachment" "data" {
  device_name  = "/dev/sdf"
  volume_id    = aws_ebs_volume.data.id
  instance_id  = module.ec2.id
  force_detach = false
}
