# Jellyseerr is a free and open source software application for managing requests for your media library.
# It is a a fork of Overseerr built to bring support for Jellyfin & Emby media servers!
#
# https://github.com/Fallenbagel/jellyseerr
# https://hub.docker.com/r/fallenbagel/jellyseerr
---
version: '3'
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=debug
      - TZ=${TIMEZONE}
    ports:
      - 5055:5055
    volumes:
      - ${DOCKER_VOLUMES}/jellyseerr:/app/config
    labels:
      - homepage.group=Arr
      - homepage.name=Jellyseerr
      - homepage.icon=jellyseerr.png
      - homepage.href=http://jellyseerr.${MYDOMAIN}/
      - homepage.description=Manage media requests