# Radarr - A fork of Sonarr to work with movies à la Couchpotato.
#
# https://hub.docker.com/r/linuxserver/radarr
---
version: "3.5"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONTAINERDATA}/radarr:/config
      - ${MEDIA}:/media
      #- ${MOVIES}:/movies #optional
      - ${DOWNLOADS}:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped