# Sonarr (formerly NZBdrone) is a PVR for usenet and bittorrent users. It can monitor multiple RSS feeds for new episodes of your favorite shows and will grab sort and rename them.
# It can also be configured to automatically upgrade the quality of files already downloaded when a better quality format becomes available.
#
# https://sonarr.tv/
# https://hub.docker.com/r/linuxserver/sonarr
---
version: "3.5"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${DOCKER_VOLUMES}/sonarr:/config
      - ${MEDIA}:/media
      - ${DOWNLOADS}:/downloads #optional
    ports:
      - 8989:8989
    labels:
      - homepage.group=Arr
      - homepage.name=Sonarr
      - homepage.icon=sonarr.png
      - homepage.href=http://sonarr.${MYDOMAIN}/
      - homepage.description=Download series