version: '3'

vars:
  TFBIN: terraform # Select "terraform" or "tofu"
  CONFIG_DIR: ../../config/terraform/azure-vm
  TFPLAN: '{{.CONFIG_DIR}}/tfplan'
  VAR_FILE: '{{.CONFIG_DIR}}/infra.tfvars'
  RESOURCE_GROUP: HomeInfra
  STORAGE_ACCOUNT_NAME: tfstateinfrandomanimal # CUSTOMIZE: Must be globally unique, 3-24 chars, lowercase letters and numbers only
  VM_NAME: nest
  VM_KEYFILE: ~/.ssh/id_rsa_azure_vm
  VM_ADMIN_USER: azureuser

env:
  TF_IN_AUTOMATION: 1

tasks:
  clean:
    desc: Clean Terraform files and plans
    cmds:
      - find . -type d -name '.terraform' -exec rm -rf {} +
      - rm -f {{.TFPLAN}}

  docs:
    desc: Update Terraform module documentation
    cmds:
      - echo 'Updating Terraform module documentation'
      - find . -name 'README.md' -not -path '*/.terragrunt-cache/*' -execdir terraform-docs markdown table --output-file README.md --output-mode inject . \;

  check:
    desc: Validate Terraform configuration and run security checks
    cmds:
      - '{{.TFBIN}} init -backend=false'
      - '{{.TFBIN}} validate'
      - tfsec

  migrate-state:
    desc: Migrate Terraform state from local to Azure remote backend
    preconditions:
      - sh: az account show
        msg: "Not logged into Azure. Run 'az login --use-device-code' first"
      - sh: az storage account show -n {{.STORAGE_ACCOUNT_NAME}} -g {{.RESOURCE_GROUP}}
        msg: "Storage account '{{.STORAGE_ACCOUNT_NAME}}' not found. Create it first (see README)"
      - sh: "[ -f '{{.CONFIG_DIR}}/terraform.tfstate' ]"
        msg: "Local state file not found at {{.CONFIG_DIR}}/terraform.tfstate"
    cmds:
      - echo "Backing up current local state..."
      - cp {{.CONFIG_DIR}}/terraform.tfstate {{.CONFIG_DIR}}/terraform.tfstate.backup-$(date +%Y%m%d-%H%M%S)
      - echo "Initializing with new backend configuration..."
      - '{{.TFBIN}} init -migrate-state'
      - echo ""
      - echo "Migration complete! Verify state in Azure:"
      - echo "  az storage blob list --account-name {{.STORAGE_ACCOUNT_NAME}} --container-name azure-vm-state --output table"

  plan:
    desc: Create Terraform plan
    vars:
      OWN_PUBLIC_IP:
        sh: curl -s https://ipinfo.io/ip
      GIT_CREDENTIALS:
        sh: cat ~/.git-credentials 2>/dev/null | head -n 1 || true
      REPO_URL:
        sh: git config --get remote.origin.url
    env:
      TF_VAR_admin_source_address: "{{.OWN_PUBLIC_IP}}"
      TF_VAR_git_credentials: "{{.GIT_CREDENTIALS}}"
      TF_VAR_repo_url: "{{.REPO_URL}}"
    cmds:
      - '{{.TFBIN}} init'
      - echo "{{.TFBIN}} plan..."
      - '{{.TFBIN}} plan -var-file="{{.VAR_FILE}}" -out="{{.TFPLAN}}"'

  apply:
    desc: Apply Terraform plan and configure SSH key
    deps: [plan]
    cmds:
      - echo "{{.TFBIN}} apply..."
      - time {{.TFBIN}} apply --auto-approve "{{.TFPLAN}}"
      - rm -f {{.TFPLAN}}
      - |
        VM_FQDN=$({{.TFBIN}} output -raw vm_fqdn)
        ssh-keygen -f ~/.ssh/known_hosts -R "$VM_FQDN" || true
        {{.TFBIN}} output -raw vm_tls_private_key > {{.VM_KEYFILE}}
        chmod 600 {{.VM_KEYFILE}}

  destroy:
    desc: Destroy all resources and remove VM key
    vars:
      OWN_PUBLIC_IP:
        sh: curl -s https://ipinfo.io/ip
      GIT_CREDENTIALS:
        sh: cat ~/.git-credentials 2>/dev/null | head -n 1 || true
      REPO_URL:
        sh: git config --get remote.origin.url
    env:
      TF_VAR_admin_source_address: "{{.OWN_PUBLIC_IP}}"
      TF_VAR_git_credentials: "{{.GIT_CREDENTIALS}}"
      TF_VAR_repo_url: "{{.REPO_URL}}"
    cmds:
      - echo "{{.TFBIN}} destroy..."
      - '{{.TFBIN}} destroy --auto-approve -var-file="{{.VAR_FILE}}" && rm -f {{.VM_KEYFILE}}'

  destroy-vm:
    desc: Destroy only the VM instance and remove VM key
    vars:
      OWN_PUBLIC_IP:
        sh: curl -s https://ipinfo.io/ip
      GIT_CREDENTIALS:
        sh: cat ~/.git-credentials 2>/dev/null | head -n 1 || true
      REPO_URL:
        sh: git config --get remote.origin.url
    env:
      TF_VAR_admin_source_address: "{{.OWN_PUBLIC_IP}}"
      TF_VAR_git_credentials: "{{.GIT_CREDENTIALS}}"
      TF_VAR_repo_url: "{{.REPO_URL}}"
    cmds:
      - echo "{{.TFBIN}} destroy..."
      - '{{.TFBIN}} destroy --auto-approve -var-file="{{.VAR_FILE}}" --target module.vm.azurerm_linux_virtual_machine.vm && rm -f {{.VM_KEYFILE}}'

  connect-vm:
    desc: SSH to the Azure VM
    cmds:
      - |
        VM_FQDN=$({{.TFBIN}} output -raw vm_fqdn)
        echo "Connecting to ${VM_FQDN}"
        ssh -i {{.VM_KEYFILE}} {{.VM_ADMIN_USER}}@${VM_FQDN}

  config-vm:
    desc: Run Ansible configuration on the Azure VM
    cmds:
      - cd ../../ansible; ./apply-cloud.sh

  keyvault-info:
    desc: Display Key Vault information and instructions
    cmds:
      - |
        echo "Key Vault Name: $({{.TFBIN}} output -raw key_vault_name)"
        echo ""
        echo "=== How to retrieve git credentials from Key Vault ==="
        echo "1. Login to Azure: az login"
        echo "2. Get credentials: az keyvault secret show --vault-name \"$({{.TFBIN}} output -raw key_vault_name)\" --name \"git-credentials\" --query \"value\" -o tsv"
        echo ""
        echo "For security, git credentials are stored securely in Azure Key Vault"

  start-vm:
    desc: Start the Azure VM
    cmds:
      - az vm start -g {{.RESOURCE_GROUP}} -n {{.VM_NAME}}

  stop-vm:
    desc: Stop the Azure VM
    cmds:
      - az vm stop -g {{.RESOURCE_GROUP}} -n {{.VM_NAME}}

  deallocate-vm:
    desc: Deallocate the Azure VM (stops billing)
    cmds:
      - az vm deallocate -g {{.RESOURCE_GROUP}} -n {{.VM_NAME}}
