name: httpbin
services:
  httpbin:
    image: ghcr.io/mccutchen/go-httpbin:2.25.0
    container_name: httpbin
    restart: unless-stopped
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.httpbin.middlewares: localaccess@file
      traefik.http.services.httpbin.loadbalancer.server.port: 8080
      homepage.group: Development
      homepage.name: httpbin
      homepage.icon: https://httpbin.org/static/favicon.ico
      homepage.href: https://httpbin.${MYDOMAIN}/
      homepage.description: HTTP request & response testing service

networks:
  proxy:
    external: true
