# https://filebrowser.org/installation
---
version: "3.5"
services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /storage:/srv
      - ${CONTAINERDATA}/filebrowser/filebrowser.db:/database/filebrowser.db
      - ${CONTAINERDATA}/filebrowser/settings.json:/config/settings.json
    ports:
      - 9030:80 # Web UI
    restart: unless-stopped