# https://hub.docker.com/r/linuxserver/syncthing
---
version: "3.5"
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: nest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${CONTAINERDATA}/syncthing:/config
      - /mnt:/data1
      #- /path/to/data2:/data2
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped