name: act-runner
services:
  act-runner:
    image: gitea/runner:3.5.0
    container_name: act-runner
    restart: unless-stopped
    environment:
      TZ: ${TIMEZONE}
      CONFIG_FILE: /config.yaml
      GITEA_INSTANCE_URL: https://gitea.${MYDOMAIN}/
      GITEA_RUNNER_REGISTRATION_TOKEN: ${GITEA_RUNNER_REGISTRATION_TOKEN}
      GITEA_RUNNER_NAME: ${GITEA_RUNNER_NAME:-act-runner}
      GITEA_RUNNER_LABELS: ${GITEA_RUNNER_LABELS:-docker:docker://node:20-bookworm,ubuntu-latest:docker://node:20-bookworm}
    volumes:
      - ${DOCKER_VOLUMES}/act-runner:/data
      - ./config/config.yaml:/config.yaml:ro
      # kics-scan ignore-line
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dev-act-runner

networks:
  dev-act-runner:
    external: true
