# Hard Drive S.M.A.R.T Monitoring, Historical Trends & Real World Failure Thresholds
#
# 📜 Source: https://github.com/AnalogJ/scrutiny
#
# In addition to the Omnibus image (available under the latest tag) you can deploy in Hub/Spoke mode
# 🐙 Compose: https://github.com/AnalogJ/scrutiny/blob/master/docker/example.hubspoke.docker-compose.yml
---
name: scrutiny-collector
services:
  scrutiny-collector:
    image: 'ghcr.io/analogj/scrutiny:master-collector'
    container_name: scrutiny-collector
    restart: unless-stopped
    cap_add:
      - SYS_RAWIO
    # kics-scan ignore-block
    volumes:
      - /run/udev:/run/udev:ro
    environment:
      COLLECTOR_API_ENDPOINT: 'https://scrutiny.${MYDOMAIN}/'
      COLLECTOR_CRON_SCHEDULE: '0 0 * * *'
    devices:
      # Only enable existing devices!
      - /dev/sda
      - /dev/sdb
      - /dev/sdc
      # - /dev/sdd
