# TODO

# brew install --cask visual-studio-code
# brew install --cask macpass

# node -> nvm (Node Version Manager)
# ruby -> rvm (Ruby Version Manager)

# https://stackoverflow.com/questions/40230184/how-to-do-multiline-shell-script-in-ansible
# asdf plugin-add kubectl https://github.com/asdf-community/asdf-kubectl.git
# asdf install kubectl 1.22.15
# asdf global kubectl 1.22.15

# python
# python3 -m pip install px-proxy

- name: Install software
  hosts: localhost
  become: false

  pre_tasks:
    - name: Ensuring Homebrew Is Installed
      stat:
        path: /opt/homebrew/bin/brew
      register: homebrew_check

    - name: Fail if Homebrew is not installed and install_homebrew_if_missing is false
      fail:
        msg: Homebrew is missing, install from http://brew.sh
      when:
        - not homebrew_check.stat.exists
        - not install_homebrew_if_missing

    - name: Installing Homebrew
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when:
        - not homebrew_check.stat.exists
        - install_homebrew_if_missing

  tasks:
    - name: Install software with brew
      community.general.homebrew:
        name: "{{ brew_base_tools + brew_cloud_tools + brew_terraform_tools + brew_kubernetes_tools }}"
        state: present
