# Unofficial Bitwarden compatible server written in Rust
#
# https://github.com/dani-garcia/vaultwarden
# https://github.com/dani-garcia/vaultwarden/wiki
# https://github.com/dani-garcia/vaultwarden/wiki/Importing-data-from-Keepass-or-KeepassX
# https://bitwarden.com/
# https://bitwarden.com/browser-start/
---
version: "3.5"
name: vaultwarden
services:
  server:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - ${DOCKER_VOLUMES}/vaultwarden:/data
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.vault.entrypoints: websecure
      traefik.http.routers.vault.rule: Host(`vault.${MYDOMAIN}`)
      traefik.http.services.vault.loadbalancer.server.port: 80
      homepage.group: Tools
      homepage.name: Vaultwarden
      homepage.icon: vaultwarden.png
      homepage.href: https://vault.${MYDOMAIN}/
      homepage.description: Password Manager

networks:
  proxy:
    external: true
