---
- name: Install base host
  hosts: all
  become: true

  tasks:
    - name: Install aptitude
      ansible.builtin.apt:
        name: aptitude
        state: present
        update_cache: true

    - name: Apt update & upgrade
      ansible.builtin.apt:
        update_cache: false
        upgrade: true
        autoremove: true

    - name: Install base packages
      ansible.builtin.apt:
        pkg: "{{ base_apt_packages }}"
        state: present
        update_cache: false

    - name: Enable passwordless sudo for members of group 'sudo'
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        regexp: "^%sudo"
        line: "%sudo ALL=(ALL:ALL) NOPASSWD: ALL"
        validate: "/usr/sbin/visudo -cf %s"
