# Jellyseerr is a free and open source software application for managing requests for your media library.
# It is a a fork of Overseerr built to bring support for Jellyfin & Emby media servers!
#
# 📜 Source: https://github.com/Fallenbagel/jellyseerr  
# 📦 Image: https://hub.docker.com/r/fallenbagel/jellyseerr  
---
version: "3.5"
name: jellyseerr
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    environment:
      LOG_LEVEL: debug
      TZ: ${TIMEZONE}
    volumes:
      - ${DOCKER_VOLUMES}/jellyseerr:/app/config
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.jellyseerr.entrypoints: websecure
      traefik.http.routers.jellyseerr.middlewares: https-local@file
      traefik.http.services.jellyseerr.loadbalancer.server.port: 5055
      homepage.group: Arr
      homepage.name: Jellyseerr
      homepage.icon: jellyseerr.png
      homepage.href: https://jellyseerr.${MYDOMAIN}/
      homepage.description: Manage media requests

networks:
  proxy:
    external: true
