---
- name: Install base host
  import_playbook: playbooks/00-base.yaml

- name: Configure admin user
  import_playbook: playbooks/05-user.yaml

- name: Configure network
  import_playbook: playbooks/10-network.yaml

- name: Mount network shares
  import_playbook: playbooks/15-samba.yaml

- name: Install Docker
  import_playbook: playbooks/20-docker.yaml
