# ansible-galaxy install -r requirements.yml
---

# Install collections from Ansible Galaxy
collections:
  # Source: https://github.com/ansible-collections/community.general
  - name: community.general
    version: 13.1.0
  # Source: https://github.com/ansible-collections/community.docker
  - name: community.docker
    version: 5.2.1
  # Source: https://github.com/ansible-collections/ansible.posix
  - name: ansible.posix
    version: 2.2.0
