# FlareSolverr is a proxy server to bypass Cloudflare protection
#
# 📦 Image: https://hub.docker.com/r/flaresolverr/flaresolverr  
# 📜 Source: https://github.com/FlareSolverr/FlareSolverr  
---
name: flaresolverr
services:
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:v3.3.24
    container_name: flaresolverr
    restart: unless-stopped
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-info}
      LOG_HTML: ${LOG_HTML:-false}
      CAPTCHA_SOLVER: ${CAPTCHA_SOLVER:-none}
      TZ: ${TIMEZONE}
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.flaresolverr.middlewares: localaccess@file
      traefik.http.services.flaresolverr.loadbalancer.server.port: 8191
      homepage.group: Arr
      homepage.name: Flaresolverr
      homepage.icon: cloudflare.png
      homepage.href: https://flaresolverr.${MYDOMAIN}/
      homepage.description: Bypass Cloudflare protection

networks:
  proxy:
    external: true
