# Prowlarr is a indexer manager/proxy built on the popular arr .net/reactjs base stack to integrate with your various PVR apps.
# Prowlarr supports both Torrent Trackers and Usenet Indexers. It integrates seamlessly with Sonarr, Radarr, Lidarr, and Readarr offering complete management
# of your indexers with no per app Indexer setup required (we do it all).
#
# 📦 Image: https://hub.docker.com/r/linuxserver/prowlarr  
# 📜 Source: https://github.com/Prowlarr/Prowlarr  
---
name: prowlarr
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:1.29.2
    container_name: prowlarr
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - ${DOCKER_VOLUMES}/prowlarr:/config
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.prowlarr.entrypoints: websecure
      traefik.http.routers.prowlarr.middlewares: https-local@file
      traefik.http.services.prowlarr.loadbalancer.server.port: 9696
      homepage.group: Arr
      homepage.name: Prowlarr
      homepage.icon: prowlarr.png
      homepage.href: https://prowlarr.${MYDOMAIN}/
      homepage.description: Arr indexer manager

networks:
  proxy:
    external: true
