# Radarr - A fork of Sonarr to work with movies à la Couchpotato.
#
# 📦 Image: https://hub.docker.com/r/linuxserver/radarr  
# 📜 Source: https://github.com/Radarr/Radarr  
---
name: radarr
services:
  radarr:
    image: lscr.io/linuxserver/radarr:5.27.5
    container_name: radarr
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - ${DOCKER_VOLUMES}/radarr:/config
      - ${STORAGE_MEDIA}:/media
      - ${STORAGE_TORRENT_DOWNLOADS}:/downloads
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.radarr.middlewares: localaccess@file
      traefik.http.services.radarr.loadbalancer.server.port: 7878
      homepage.group: Arr
      homepage.name: Radarr
      homepage.icon: radarr.png
      homepage.href: https://radarr.${MYDOMAIN}/
      homepage.description: Download movies

networks:
  proxy:
    external: true
