# Hard Drive S.M.A.R.T Monitoring, Historical Trends & Real World Failure Thresholds
#
# https://github.com/AnalogJ/scrutiny
---
version: "3.5"
services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
    ports:
      - 8085:8080 # webapp
      - 8086:8086 # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - ${CONTAINERDATA}/scrutiny/config:/opt/scrutiny/config
      - ${CONTAINERDATA}/scrutiny/influxdb
    devices:
      - /dev/sda
      - /dev/sdb
      - /dev/sdc
      - /dev/sdd
    restart: unless-stopped