---
- name: Create admin user '{{ admin_user }}'
  ansible.builtin.user:
    name: "{{ admin_user }}"
    password: "{{ admin_password | password_hash('sha512') }}"
    comment: "{{ admin_name }}"
    groups:
      - sudo
    shell: '/bin/bash'
    append: true
    update_password: on_create

- name: Configure SSH key
  when: configure_ssh_key|default(false)|bool
  block:
  - name: Create .ssh folder for user '{{ admin_user }}'
    ansible.builtin.file:
      path: "~{{ admin_user }}/.ssh"
      owner: "{{ admin_user }}"
      group: "{{ admin_user }}"
      state: directory
      mode: '0700'
  - name: Set authorized key for user '{{ admin_user }}'
    ansible.posix.authorized_key:
      user: "{{ admin_user }}"
      state: present
      key: "{{ lookup('file', ssh_key_file) }}"

- name: Set git global config for user '{{ admin_user }}'
  community.general.git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  become_user: "{{ admin_user }}"
  with_items:
    - name: "user.name"
      value: "{{ admin_name }}"
    - name: "user.email"
      value: "{{ admin_email }}"
    - name: "credential.helper"
      value: "store"
    - name: "pull.rebase"
      value: "true"
