---
- name: Install and update apt packages
  ansible.builtin.import_tasks: 10-apt.yaml

- name: Security configuration
  ansible.builtin.import_tasks: 30-security.yaml

- name: Configure network
  ansible.builtin.import_tasks: 40-network.yaml

- name: Configure admin user
  ansible.builtin.import_tasks: 50-user.yaml
