---
- name: Check if go-task is already installed
  ansible.builtin.command: task --version
  register: debian_base_task_version_check
  changed_when: false
  failed_when: false

- name: Ensure tmp directory exists
  ansible.builtin.file:
    path: /tmp/go-task
    state: directory
    mode: "0755"
  when: debian_base_task_version_check.rc != 0

- name: Fail on unsupported architecture
  ansible.builtin.fail:
    msg: "Unsupported architecture: {{ ansible_facts['architecture'] }}"
  when: ansible_facts['architecture'] not in ["x86_64", "aarch64", "armv7l", "armv6l"]

- name: Set go-task architecture
  ansible.builtin.set_fact:
    debian_base_task_arch: "{{ {'x86_64': 'amd64', 'aarch64': 'arm64', 'armv7l': 'arm', 'armv6l': 'arm'}[ansible_facts['architecture']] }}"

- name: Set go-task version
  ansible.builtin.set_fact:
    debian_base_go_task_version: "{{ debian_base_go_task_version | default('v3.50.0') }}"

- name: Download go-task .deb package
  ansible.builtin.get_url:
    url: "https://github.com/go-task/task/releases/download/{{ debian_base_go_task_version }}/task_{{ debian_base_go_task_version | regex_replace('^v', '') }}_linux_{{ debian_base_task_arch }}.deb"
    dest: "/tmp/go-task/task_{{ debian_base_go_task_version }}_linux_{{ debian_base_task_arch }}.deb"
    mode: "0644"
  when: debian_base_task_version_check.rc != 0

- name: Install go-task from downloaded .deb package
  ansible.builtin.apt:
    deb: "/tmp/go-task/task_{{ debian_base_go_task_version }}_linux_{{ debian_base_task_arch }}.deb"
    state: present
  when: debian_base_task_version_check.rc != 0

- name: Clean up temporary files
  ansible.builtin.file:
    path: /tmp/go-task
    state: absent
  when: debian_base_task_version_check.rc != 0
