# > [Kiwix](https://kiwix.org/) is a non-profit organization and a free and open-source software project dedicated to providing offline access to free educational content.
# > We can make highly compressed copies of entire websites that each fit into a single (.zim) file. Zim files are small enough that they can be stored on users’ mobile phones, computers or small, inexpensive Hotspot.
# > Kiwix then acts like a regular browser, except that it reads these local copies. People with no or limited internet access can enjoy the same browsing experience as anyone else.
#
# Download content (`.zim` files) from https://library.kiwix.org/, place into `${STORAGE_KIWIX}` and restart the container.  
# More information on the `.zim` files: https://download.kiwix.org/zim/README  
#
# Container: https://github.com/kiwix/kiwix-tools/pkgs/container/kiwix-serve  
# Applications for multiple platforms: https://kiwix.org/en/applications/  
# Android APK (supports sideloaded `.zim` files): https://download.kiwix.org/release/kiwix-android/  
---
name: kiwix-serve
services:
  homelab-docs:
    image: ghcr.io/kiwix/kiwix-serve:3.7.0
    container_name: kiwix-serve
    command:
      '*.zim'
    restart: unless-stopped
    volumes:
      - ${STORAGE_KIWIX}:/data
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.homelab-docs.entrypoints: websecure
      traefik.http.routers.homelab-docs.middlewares: https-local@file
      traefik.http.routers.homelab-docs.rule: Host(`kiwix.${MYDOMAIN}`)
      traefik.http.services.homelab-docs.loadbalancer.server.port: 8080
      homepage.group: Media
      homepage.name: Kiwix server
      homepage.icon: kiwix.png
      homepage.href: https://kiwix.${MYDOMAIN}/
      homepage.description: Offline access to free educational content

networks:
  proxy:
    external: true
